#+TITLE: Postmodern Reference Manual
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>
#+OPTIONS: ^:nil
#+OPTIONS: toc:2

This is the reference manual for the component named postmodern, which is part
of a library of the same name.

Note that this package also exports the database-connection and database-error
types from CL-postgres and a few operators from S-SQL.

query, execute, and any other function that would logically need to communicate
with the database will raise a condition of the type database-error when
something goes wrong. As a special case, errors that break the connection
(socket errors, database shutdowns) will be raised as subtypes of
database-connection-error, providing a :reconnect restart to re-try the
operation that encountered to the error.

* Connecting
  :PROPERTIES:
  :ID:       75c23b08-3840-4d28-8ced-978d10a629d5
  :CUSTOM_ID: connecting
  :END:
** class database-connection
   :PROPERTIES:
   :ID:       821e500c-5206-4f8b-a505-266d18faf8cb
   :CUSTOM_ID: dfc95b36-94d7-42ab-827b-8622f593e7f6
   :END:

Representation of a database connection. Contains login information in order to
be able to automatically re-establish a connection when it is somehow closed.

** function connect (database user-name password host &key (port 5432) pooled-p use-ssl)
   :PROPERTIES:
   :ID:       66e24327-bae9-4378-987c-ccdacc312ddf
   :CUSTOM_ID: d4aa3e04-ab90-4271-b3e7-60a48e4f2e49
   :END:
→ database-connection

Create a new database connection for the given user and the database. Port will
default to 5432, which is where most PostgreSQL servers are running. If
pooled-p is T, a connection will be taken from a pool of connections of this
type, if one is available there, and when the connection is disconnected it will
be put back into this pool instead. use-ssl can be :no, :try, :require, :yes, or :full
and defaults to the value of *default-use-ssl*

- :try means if the server supports it
- :require means use provided ssl certificate with no verification
- :yes means verify that the server cert is issued by a trusted CA, but does not verify the server hostname
- :full means expect a CA-signed cert for the supplied hostname and verify the server hostname
If you set it to anything other than :no be sure to also load the CL+SSL library.

** variable *default-use-ssl*
   :PROPERTIES:
   :ID:       106f14f7-270e-4e27-a238-34c50b14e44b
   :CUSTOM_ID: e140fab3-b6fe-4e88-b9ca-241bbb64fce4
   :END:

The default for connect's use-ssl argument.
Valid settings are :no, :try, :require, :yes, or :full
:try means if the server supports it
:require means use provided ssl certificate with no verification
:yes means verify that the server cert is issued by a trusted CA, but does not verify the server hostname
:full means expect a CA-signed cert for the supplied hostname and verify the server hostname
If you set it to anything other than :no be sure to also load the CL+SSL library.

** method disconnect (database-connection)
   :PROPERTIES:
   :ID:       4c9746be-27ce-485c-b35e-d739e7def9c4
   :CUSTOM_ID: 9a1a03af-a67e-4419-9066-d79a81885f81
   :END:

Disconnects a normal database connection, or moves a pooled connection into the
pool.

** function connected-p (database-connection)
   :PROPERTIES:
   :ID:       d9f11a8d-3676-42e9-aee9-a544ef67df28
   :CUSTOM_ID: a660d0cc-4795-41df-b183-0ea31f6b6584
   :END:
→ boolean

Returns a boolean indicating whether the given connection is still connected to
the server.

** method reconnect (database-connection)
   :PROPERTIES:
   :ID:       6e117ba4-b3f7-48f3-9616-67e3c3e2b7e4
   :CUSTOM_ID: 426a8f5d-5dc7-4973-a1fc-11b488afcd82
   :END:

Reconnect a disconnected database connection. This is not allowed for pooled
connections ― after they are disconnected they might be in use by some other
process, and should no longer be used.

** variable *database*
   :PROPERTIES:
   :ID:       73c9e729-4db7-4ef3-a095-7b91a9db6238
   :CUSTOM_ID: 9b9cf868-214b-4026-8f80-25b23f445c91
   :END:

Special variable holding the current database connection information. Most
functions and macros operating on a database assume this binds to a connected
database.

** macro with-connection (spec &body body)
   :PROPERTIES:
   :ID:       c5d5b7f9-9555-4a0e-b691-1b10742e482d
   :CUSTOM_ID: 056d4921-c834-4655-a487-83314f22da42
   :END:

Evaluates the body with *database* bound to a connection as specified by spec,
which should be list that connect can be applied to.

** macro call-with-connection (spec thunk)
   :PROPERTIES:
   :ID:       476f90d8-15ac-49fb-ac19-1dc3dfdfcef7
   :CUSTOM_ID: 0e0c03e9-7681-433f-ae75-8f06c9685221
   :END:

The functional backend to with-connection. Binds *database* to a new connection
as specified by spec, which should be a list that connect can be applied to, and
runs the zero-argument function given as second argument in the new environment.
When the function returns or throws, the new connection is disconnected.

** function connect-toplevel (database user-name password host &key (port 5432))
   :PROPERTIES:
   :ID:       ffab8aae-0ed7-4466-a68d-fc90d2e36dbe
   :CUSTOM_ID: a74be5d0-9b86-4c15-b738-76cd92908d25
   :END:

Bind the *database* to a new connection. Use this if you only need one
connection, or if you want a connection for debugging from the REPL.

** function disconnect-toplevel ()
   :PROPERTIES:
   :ID:       f5819286-2754-468d-bfdd-e4ee06b877e3
   :CUSTOM_ID: a63f929c-805d-42d5-8fbe-f1c01e62b50a
   :END:

Disconnect the *database*.

** function clear-connection-pool ()
   :PROPERTIES:
   :ID:       04d09496-6a7b-4794-a204-8667f3b69011
   :CUSTOM_ID: 56c370e4-8f4e-414a-82b6-ae4408fc0b61
   :END:

Disconnect and remove all connections from the connection pools.

** variable *max-pool-size*
   :PROPERTIES:
   :ID:       92ab48e3-bf8f-4327-8d9c-69b6c168f94e
   :CUSTOM_ID: 97aa1ebb-ef91-4254-a6b7-bfcd8128ad96
   :END:

Set the maximum amount of connections kept in a single connection pool, where a
pool consists of all the stored connections with the exact same connect
arguments. Defaults to NIL, which means there is no maximum.

** function list-connections ()
   :PROPERTIES:
   :ID:       1410d2f2-3f68-4e3d-947b-46167ecf1d37
   :CUSTOM_ID: 09583f9a-388a-400a-bb3c-d118242508c8
   :END:
→ list

List the current postgresql connections to the currently connected database. It
does this by returningo info from pg_stat_activity on open connections.
* Querying
  :PROPERTIES:
  :ID:       e5e99216-0a15-4de8-b1d9-21bdcdf378fa
  :CUSTOM_ID: querying
  :END:
** macro query (query &rest args/format)
   :PROPERTIES:
   :ID:       0f8ab85f-b592-4648-8936-d16abce50faa
   :CUSTOM_ID: 5a8c24fb-6d7b-4952-8520-b5e8ea98dd77
   :END:
→ result

Execute the given query, which can be either a string or an S-SQL form
(list starting with a keyword). If the query contains placeholders ($1, $2, etc)
their values can be given as extra arguments. If one of these arguments
is a keyword occurring in the table below, it will not be used as a query
argument, but will determine the format in which the results are returned
instead. Any of the following formats can be used, with the default being :rows:

| :none	             | Ignore the result values.                                                                                                                                |
| :lists, :rows       | 	Return a list of lists, each list containing the values for a row.                                                                                     |
| :list, :row         | 	Return a single row as a list.                                                                                                                         |
| :alists	           | Return a list of alists which map column names to values, with the names represented as keywords.                                                        |
| :alist	            | Return a single row as an alist.                                                                                                                         |
| :str-alists         | 	Like :alists, but use the original column names.                                                                                                       |
| :str-alist	        | Return a single row as an alist, with strings for names.                                                                                                 |
| :plists	           | Return a list of plists which map column names to values,with the names represented as keywords.                                                         |
| :plist	            | Return a single row as a plist.                                                          |
| :column	           | Return a single column as a list.                 |
| :single	           | Return a single value. Will raise an error if the query returns more than one field. If the query returns more than one row, it returns the first row. |
| :single!	          | Like :single except that it will throw an error when the number of selected rows is not equal to 1.  |
| :array-hash         | Return an array of hashtables which map column names to hash table keys     |
| :json-strs          | Return a list of strings where each row is a json object expressed as a string  |
| :json-strs          | Return a single string where the row returned is a json object expressed as a string           |
| :json-array-str     | Return a string containing a json array, each element in the array is a selected row expressed as a json object |
| (:dao type)	       | Return a list of DAOs of the given type. The names of the fields returned by the query must match slots in the DAO class the same way as with query-dao. |
| (:dao type :single) | 	Return a single DAO of the given type. |

Some Examples:
*** Default
The default is :lists
#+BEGIN_SRC lisp
(query (:select 'id 'int4 'text :from 'short-data-type-tests :where (:< 'id 3)))
((1 2147483645 "text one") (2 0 "text two"))
#+END_SRC
*** Single
Returns a single field. Will throw an error if the queries returns more than one field or more than one row
#+BEGIN_SRC lisp
(query (:select 'text :from 'short-data-type-tests :where (:= 'id 3)) :single)
"text three"
#+END_SRC
*** List
Returns a list containing the selected fields. Will throw an error if the query returns more than one row
#+BEGIN_SRC lisp
(query (:select 'id 'int4 'text :from 'short-data-type-tests :where (:= 'id 3)) :list)
(3 3 "text three")
#+END_SRC
*** Lists
This is the default
#+BEGIN_SRC lisp
(query (:select 'id 'int4 'text :from 'short-data-type-tests :where (:< 'id 3)) :lists)
((1 2147483645 "text one") (2 0 "text two"))
#+END_SRC
*** Alist
Returns an alist containing the field name as a keyword and the selected fields. Will throw an error if the query returns more than one row.
#+BEGIN_SRC lisp
(query (:select 'id 'int4 'text :from 'test-data :where (:= 'id 3)) :alist)
((:ID . 3) (:INT4 . 3) (:TEXT . "text three"))
#+END_SRC
*** Str-alist
Returns an alist containing the field name as a lower case string and the selected fields. Will throw an error if the query returns more than one row.
#+BEGIN_SRC lisp
(query (:select 'id 'int4 'text :from 'short-data-type-tests :where (:= 'id 3)) :str-alist)
(("id" . 3) ("int4" . 3) ("text" . "text three"))
#+END_SRC

*** Alists
Returns a list of alists containing the field name as a keyword and the selected fields.
#+BEGIN_SRC lisp
(query (:select 'id 'int4 'text :from 'short-data-type-tests :where (:< 'id 3)) :alists)
(((:ID . 1) (:INT4 . 2147483645) (:TEXT . "text one"))
 ((:ID . 2) (:INT4 . 0) (:TEXT . "text two")))
#+END_SRC
*** Str-alists
Returns a list of alists containing the field name as a lower case string and the selected fields.
#+BEGIN_SRC lisp
(query (:select 'id 'int4 'text :from 'short-data-type-tests :where (:< 'id 3)) :str-alists)
((("id" . 1) ("int4" . 2147483645) ("text" . "text one"))
 (("id" . 2) ("int4" . 0) ("text" . "text two")))
#+END_SRC
*** Plist
Returns a plist containing the field name as a keyword and the selected fields. Will throw an error if the query returns more than one row.
#+BEGIN_SRC lisp
(query (:select 'id 'int4 'text :from 'short-data-type-tests :where (:= 'id 3)) :plist)
(:ID 3 :INT4 3 :TEXT "text three")
#+END_SRC
*** Plists
Returns a list of plists containing the field name as a keyword and the selected fields.
#+BEGIN_SRC lisp
(query (:select 'id 'int4 'text :from 'short-data-type-tests :where (:< 'id 3)) :plists)
((:ID 1 :INT4 2147483645 :TEXT "text one") (:ID 2 :INT4 0 :TEXT "text two"))
#+END_SRC
*** Array-hash
Returns a vector of hashtables where each hash table is a returned row from the query with field name as the key expressed as a lower case string.
#+BEGIN_SRC lisp
(query (:select 'id 'int4 'text :from 'short-data-type-tests :where (:< 'id 3)) :array-hash)
#(#<HASH-TABLE :TEST EQUAL :COUNT 3 {100D982B53}>
  #<HASH-TABLE :TEST EQUAL :COUNT 3 {100D982ED3}>)

(alexandria:hash-table-alist
  (aref
    (query (:select 'id 'int4 'text :from 'short-data-type-tests :where (:< 'id 3)) :array-hash)
    1))
(("text" . "text two") ("int4" . 0) ("id" . 2))
#+END_SRC
*** Dao
Returns a list of daos of the type specified
#+BEGIN_SRC lisp
(query (:select '* :from 'country) (:dao country))
(#<COUNTRY {1010464023}> #<COUNTRY {1010465CB3}>)

(query (:select '* :from 'country :where (:= 'name "Croatia")) (:dao country))
(#<COUNTRY {1010688943}>)
#+END_SRC
*** Column
Returns a list of field values of a single field. Will throw an error if more than one field is selected
#+BEGIN_SRC lisp
(query (:select 'id :from 'short-data-type-tests :where (:< 'id 3)) :column)
(1 2)

(query (:select 'id :from 'short-data-type-tests :where (:= 'id 3)) :column)
(3)
#+END_SRC
*** Json-strs
Return a list of strings where the row returned is a json object expressed as a string
#+BEGIN_SRC lisp
(query (:select 'id 'int4 'text :from 'short-data-type-tests :where (:< 'id 3)) :json-strs)
("{\"id\":1,\"int4\":2147483645,\"text\":\"text one\"}"
 "{\"id\":2,\"int4\":0,\"text\":\"text two\"}")
#+END_SRC
This will also handle local-time timestamps and simple-date timestamps,
time-of-day and date. E.g. (with a local-time timestamp)
#+BEGIN_SRC lisp
(query (:select 'timestamp-with-time-zone
        :from 'test-data
        :where (:< 'id 3))
  :json-strs)

'("{\"timestampWithTimeZone\":\"{2019-12-30T13:30:54.000000-05:00}\"}"
  "{\"timestampWithTimeZone\":\"{1919-12-30T13:30:54.000000-05:00}\"}")
#+END_SRC

The following is an example with a simple-date timestamp.
#+BEGIN_SRC lisp
(query (:select 'timestamp-with-time-zone
                       :from 'test-data
                       :where (:< 'id 3)) :json-strs)
'("{\"timestampWithTimeZone\":\"2019-12-30 18:30:54:0\"}"
  "{\"timestampWithTimeZone\":\"1919-12-30 18:30:54:0\"}")
#+END_SRC
*** Json-str
Return a single string where the row returned is a json object expressed as a string
#+BEGIN_SRC lisp
(query (:select 'id 'int4 'text :from 'short-data-type-tests :where (:= 'id 3)) :json-str)
"{\"id\":3,\"int4\":3,\"text\":\"text three\"}"
#+END_SRC
As with :json-strs, this will also work for either simple-date or local-time timestamps

*** Json-array-str
Return a string containing a json array, each element in the array is a selected row expressed as a json object
#+BEGIN_SRC lisp
(query (:select 'id 'int4 'text :from 'short-data-type-tests :where (:< 'id 3)) :json-array-str)
"[{\"id\":1,\"int4\":2147483645,\"text\":\"text one\"}, {\"id\":2,\"int4\":0,\"text\":\"text two\"}]"
#+END_SRC
As with :json-strs, this will also work for either simple-date or local-time timestamps
*** Second value returned
If the database returns information about the amount rows that were affected,
such as with updating or deleting queries, this is returned as a second value.

** macro execute (query &rest args)
   :PROPERTIES:
   :ID:       b494a547-353c-4de4-8071-e8703a62b919
   :CUSTOM_ID: 71106869-4169-49c8-ba7d-ce6b9fc7d780
   :END:

Execute a query, ignore the results. So, in effect, Like a query called with
format :none. Returns the amount of affected rows as its first returned value.
(Also returns this amount as the second returned value, but use of this is
deprecated.)

** macro doquery (query (&rest names) &body body)
   :PROPERTIES:
   :ID:       db023195-6f0f-446d-9188-0886d895202b
   :CUSTOM_ID: 66aa9f57-ac8a-4457-9891-3453682518e0
   :END:

Execute the given query (a string or a list starting with a keyword), iterating
over the rows in the result. The body will be executed with the values in the
row bound to the symbols given in names. To iterate over a parameterised query,
one can specify a list whose car is the query, and whose cdr contains the
arguments. For example:
#+BEGIN_SRC lisp
(doquery (:select 'name 'score :from 'scores) (n s)
  (incf (gethash n *scores*) s))

(doquery ((:select 'name :from 'scores :where (:> 'score '$1)) 100) (name)
  (print name))
#+END_SRC

** macro prepare (query &optional (format :rows))
   :PROPERTIES:
   :ID:       0daaa786-45e9-4853-934c-e1499b4c87f0
   :CUSTOM_ID: 625b6ade-7b09-49dc-b288-78c550b25d83
   :END:
→ function

Wraps a query into a function that can be used as the interface to a prepared
statement. The given query (either a string or an S-SQL form) may contain
placeholders, which look like $1, $2, etc. The resulting function takes one
argument for every placeholder in the query, executes the prepared query, and
returns the result in the format specified. (Allowed formats are the same as for
query.)

For queries that have to be run very often, especially when they are complex,
it may help performance since the server only has to plan them once. See the [[http://www.postgresql.org/docs/current/static/sql-prepare.html][
PostgreSQL manual]] for details.

In some cases, the server will complain about not being able to deduce the type
of the arguments in a statement. In that case you should add type declarations
(either with the PostgreSQL's CAST SQL-conforming syntax or
historical :: syntax, or with S-SQL's :type construct) to help it out.

Note that it will attempt to automatically reconnect if
database-connection-error, or admin-shutdown. It will reset prepared statements
triggering an invalid-sql-statement-name error. It will overwrite old prepared
statements triggering a duplicate-prepared-statement error.

** macro defprepared (name query &optional (format :rows))
   :PROPERTIES:
   :ID:       d95a6214-b951-4fcd-96ab-a0c40d62ee2b
   :CUSTOM_ID: b2ed5fb5-d5f5-4425-b30e-5c40a2997eee
   :END:
→ function

This is the macro-style variant of prepare. It is like prepare, but gives the
function a name which now becomes a top-level function for the prepared
statement. The name should not a string but may be quoted.

** macro defprepared-with-names (name (&rest args) (query &rest query-args) &optional (format :rows))
   :PROPERTIES:
   :ID:       b29f3cc1-4af4-4619-9817-ecbc06d98d51
   :CUSTOM_ID: 73823e7b-1fc5-40b2-908f-cec99ac1bc9e
   :END:

Like defprepared, but allows to specify names of the function arguments in a
lambda list as well as arguments supplied to the query.
#+BEGIN_SRC lisp
(defprepared-with-names user-messages (user &key (limit 10))
  ("select * from messages
    where user_id = $1
    order by date desc
    limit $2" (user-id user) limit)
  :plists)
#+END_SRC

** macro with-transaction ((&optional name isolation-level) &body body)
   :PROPERTIES:
   :ID:       29d50700-9459-4e40-baaa-efafc7fbe0cf
   :CUSTOM_ID: 453612e6-2835-41b2-8305-01b6b5473138
   :END:

Execute the given body within a database transaction, committing it when the
body exits normally, and aborting otherwise. An optional name and/or
isolation-level can be given to the transaction. The name can be used to
force a commit or abort before the body unwinds. The isolation-level
will set the isolation-level used by the transaction.

You can specify the following isolation levels in postmodern transactions:

- :read-committed-rw (read committed with read and write)
- :read-committed-ro (read committed with read only)
- :repeatable-read-rw (repeatable read with read and write)
- :repeatable-read-ro (repeatable read with read only)
- :serializable (serializable with reand and write)

Sample usage where "george" is just the name given to the transaction (not
quoted or a string) and ... simply indicates other statements would be
expected here:
#+BEGIN_SRC lisp
(with-transaction ()
  (execute (:insert-into 'test-data :set 'value 77))
  ...)

(with-transaction (george)
  (execute (:insert-into 'test-data :set 'value 22))
  ...)

(with-transaction (george :read-committed-rw)
  (execute (:insert-into 'test-data :set 'value 33))
  (query (:select '* :from 'test-data))
  ...)

(with-transaction (:serializable)
  (execute (:insert-into 'test-data :set 'value 44))
  ...)
#+END_SRC

Further discussion of transactions and isolation levels can found at
[[file:isolation-notes.html][isolation-notes.html]] in the doc directory.

** function commit-transaction (transaction)
   :PROPERTIES:
   :ID:       c5f3a2df-ebef-4180-af02-f54921552736
   :CUSTOM_ID: 10b5d3e9-b174-4f02-8c47-6eb3430e60fe
   :END:

Immediately commit an open transaction.

** function abort-transaction (transaction)
   :PROPERTIES:
   :ID:       6c705c87-8bd9-41cd-b63a-7ef67d5691f6
   :CUSTOM_ID: 58a7459f-a1f4-4797-83b5-8b5257ca2cf7
   :END:

Roll back the given transaction, but the transaction
block is still active. Thus calling abort-transaction in the middle of a
transaction does not end the transaction. Any subsequent statements will still
be executed. Per the Postgresql documentation: ABORT rolls back the current
transaction and causes all the updates made by the transaction to be discarded.
This command is identical in behavior to the standard SQL command ROLLBACK, and
is present only for historical reasons..

** function rollback-transaction (transaction)

Roll back the given transaction, but the transaction
block is still active. Thus calling abort-transaction in the middle of a
transaction does not end the transaction. Any subsequent statements will still
be executed. Per the Postgresql documentation: this rolls back the current
transaction and causes all the updates made by the transaction to be discarded.

** macro with-savepoint (name &body body)
   :PROPERTIES:
   :ID:       2b3980a2-969c-4376-92aa-ce9ee5867b6c
   :CUSTOM_ID: 5899097b-a5fb-4b7a-961b-3c65a95f81d4
   :END:

Can only be used within a transaction. Establishes a savepoint with the given
name at the start of body, and binds the same name to a handle for that
savepoint. The body is executed and, at the end of body, the savepoint is
released, unless a condition is thrown, in which case it is rolled back.
Execute the body within a savepoint, releasing savepoint when the body exits
normally, and rolling back otherwise. NAME is both the variable that can be
used to release or rolled back before the body unwinds, and the SQL name of the
savepoint.

The following example demonstrates with-savepoint, rollback-savepoint and
release-savepoint.

#+BEGIN_SRC lisp
(execute (:create-table test-data ((value :type integer))))

(defun test12 (x &optional (y nil))
  (with-logical-transaction (lt1 :read-committed-rw)
    (execute (:insert-into 'test-data :set 'value 0))
    (with-savepoint sp1
      (execute (:insert-into 'test-data :set 'value 1))
      (format t "1-1. ~a Savepoint-name ~a~%" (query "select * from test_data")
              (pomo::savepoint-name sp1))
      (if (< x 0)
          (rollback-savepoint sp1)
          (release-savepoint sp1))
      (format t "1-2. ~a~%" (query "select * from test_data")))
    (with-savepoint sp2
      (execute (:insert-into 'test-data :set 'value 2))
      (format t "2-1. ~a Savepoint-name ~a~%" (query "select * from test_data")
              (pomo::savepoint-name sp2))
      (with-savepoint sp3
        (execute (:insert-into 'test-data :set 'value 3))
        (format t "3-1. ~a Savepoint-name ~a~%" (query "select * from test_data")
                (pomo::savepoint-name sp3))
        (if (> x 0)
            (rollback-savepoint sp3)
            (release-savepoint sp3))
        (format t "3-2. ~a~%" (query "select * from test_data"))
        (when y (rollback-savepoint sp2))
        (format t "3-3. ~a~%" (query "select * from test_data")))
      (if (= x 0)
          (rollback-savepoint sp2)
          (release-savepoint sp2))
      (format t "2-2. ~a~%" (query "select * from test_data")))
    (format t "4. ~a~%" (query "select * from test_data"))
    (when (string= y "abrt")
      (abort-transaction lt1))
    (format t "5. ~a~%" (query "select * from test_data"))))
#+END_SRC

** function release-savepoint (savepoint)
   :PROPERTIES:
   :ID:       1d876de8-f717-4a15-a222-18aa4c344583
   :CUSTOM_ID: a6d99838-ed98-4839-ac13-c03ecbfd6f96
   :END:

Immediately release a savepoint, commiting its results.

** function rollback-savepoint (savepoint)
   :PROPERTIES:
   :ID:       a19e709e-b574-4494-bb79-aa788fcc0200
   :CUSTOM_ID: 1f84633f-e567-42c6-bcfc-2167dad89165
   :END:

Immediately roll back a savepoint, aborting the results.

** method commit-hooks (transaction-or-savepoint), setf (commit-hooks transaction-or-savepoint)
   :PROPERTIES:
   :ID:       c297fecf-bcb8-451c-bd91-22892d04c96d
   :CUSTOM_ID: 919494ae-625f-4f63-b271-6cc5d0b16549
   :END:

An accessor for the transaction or savepoint's list of commit hooks, each of
which should be a function with no required arguments. These functions will be
executed when a transaction is committed or a savepoint released.

** function abort-hooks (transaction-or-savepoint), setf (abort-hooks transaction-or-savepoint)
   :PROPERTIES:
   :ID:       7dd2980a-9f3d-4bff-a1f5-0745adecba24
   :CUSTOM_ID: 94700fa6-1f29-4c0f-86ad-487e640933b9
   :END:

An accessor for the transaction or savepoint's list of abort hooks, each of
which should be a function with no required arguments. These functions will be
executed when a transaction is aborted or a savepoint rolled back (whether via a
non-local transfer of control or explicitly by either abort-transaction or
rollback-savepoint).

** variable *isolation-level*
   :PROPERTIES:
   :ID:       01275b50-0fa5-4b2f-968f-c360bc3efde0
   :CUSTOM_ID: 44dac415-f1b2-4f01-bb05-a31c6c977b4c
   :END:

The transaction isolation level currently in use. Defaults to :read-committed-rw

You can specify the following isolation levels in postmodern transactions:

- :read-committed-rw (read committed with read and write)
- :read-committed-ro (read committed with read only)
- :repeatable-read-rw (repeatable read with read and write)
- :repeatable-read-ro (repeatable read with read only)
- :serializable (serializable with reand and write)


** macro with-logical-transaction ((&optional name isolation-level) &body body)
   :PROPERTIES:
   :ID:       355157ce-0f0c-4f9a-9be0-cfd12fd7bea0
   :CUSTOM_ID: 5fdcafe3-5da4-48ee-8bb0-8567c7e00837
   :END:

Executes body within a with-transaction form if no transaction is currently
in progress, otherwise simulates a nested transaction by executing it
within a with-savepoint form. The transaction or savepoint is bound to name
if one is supplied. The isolation-level will set the isolation-level used by the
transaction.

You can specify the following isolation levels in postmodern transactions:

- :read-committed-rw (read committed with read and write)
- :read-committed-ro (read committed with read only)
- :repeatable-read-rw (repeatable read with read and write)
- :repeatable-read-ro (repeatable read with read only)
- :serializable (serializable with reand and write)

For more information see [[file:isolation-notes.html][isolation-notes]]

Sample usage where "george" is just the name given to the transaction (not
quoted or a string) and ... simply indicates other statements would be
expected here:

#+BEGIN_SRC lisp
(with-logical-transaction ()
  (execute (:insert-into 'test-data :set 'value 77))
  ...)

(with-logical-transaction (george)
  (execute (:insert-into 'test-data :set 'value 22))
  ...)

(with-logical-transaction (george :read-committed-rw)
  (execute (:insert-into 'test-data :set 'value 33))
  ...)

(with-logical-transaction (:serializable)
  (execute (:insert-into 'test-data :set 'value 44))
  ...)
#+END_SRC

** function abort-logical-transaction (transaction-or-savepoint)
   :PROPERTIES:
   :ID:       196ef5b0-9c58-4f28-9766-e37334448d3c
   :CUSTOM_ID: 7d237c64-5c3e-44a6-8b7c-6eecc4379b71
   :END:

Roll back the given logical transaction, regardless of whether it is an actual
transaction or a savepoint.

** function commit-logical-transaction (transaction-or-savepoint)
   :PROPERTIES:
   :ID:       33fd01cd-603f-48e0-a2d9-1433d9b7f4db
   :CUSTOM_ID: ae0f0c99-0bda-491e-99a5-3a61e0a86166
   :END:

Commit the given logical transaction, regardless of whether it is an actual
transaction or a savepoint.

** variable *current-logical-transaction*
   :PROPERTIES:
   :ID:       2a5d91c2-f990-4a3c-a775-5e1fd539fee8
   :CUSTOM_ID: bf78478f-92a2-4162-963d-b4e101b23154
   :END:

This is bound to the current transaction-handle or savepoint-handle instance
representing the innermost open logical transaction.

** macro ensure-transaction (&body body)
   :PROPERTIES:
   :ID:       34881db5-1c47-444e-bb55-bb6249d4764c
   :CUSTOM_ID: 6ad767b2-75b7-48ee-a260-6caece5bad62
   :END:

Ensures that body is executed within a transaction, but does not begin a new
transaction if one is already in progress.

** macro ensure-transaction-with-isolation-level (isolation-level &body body)
   :PROPERTIES:
   :ID:       dba390df-3c75-4d4c-b8c9-79af3f763914
   :CUSTOM_ID: 9ca2ed2b-60ea-4e34-b370-a4f54c1f1dcd
   :END:

Executes body within a with-transaction form if and only if no transaction is
already in progress. This adds the ability to specify an isolation level other
than the current default

* Helper functions for Prepared Statements
  :PROPERTIES:
  :ID:       d4846b02-aa2f-4e44-9294-7e5811e61e6c
  :CUSTOM_ID: prepared-statement-helper-functions
  :END:

** defparameter *allow-overwriting-prepared-statements*
   :PROPERTIES:
   :ID:       ca5ba066-3d35-4bb1-97b1-c22436c1bc6d
   :CUSTOM_ID: 533331a5-6780-41bd-9ae8-2efac3a3c2c2
   :END:

When set to t, ensured-prepared will overwrite prepared statements having the
same name if the query statement itself in the postmodern meta connection is
different than the query statement provided to ensure-prepared.

** function prepared-statement-exists-p (name)
   :PROPERTIES:
   :ID:       a9d22ab2-b849-475c-b325-a91638aed7a0
   :CUSTOM_ID: 7ca58f04-2ad5-4896-b8c2-b13b276b4f5b
   :END:
→ boolean
This returns t if the prepared statement exists in the current postgresql
session, otherwise nil.

** function list-prepared-statements (&optional (names-only nil))
   :PROPERTIES:
   :ID:       0028b494-ebd0-40ca-ac31-a4ae7b598609
   :CUSTOM_ID: 3788ef72-d6a7-4e3b-acad-3f2608914dfb
   :END:
→ list

This is syntactic sugar. It runs a query that lists the prepared statements in
the session in which the function is run. If the names-only parameter is set
to t, it will only return a list of the names of the prepared statements.

** function drop-prepared-statement (statement-name &key (location :both) (database *database*))
   :PROPERTIES:
   :ID:       7ce9f5ff-3750-4359-9850-e9a23b0a279a
   :CUSTOM_ID: 7ec6297f-85a7-419e-a9d4-8f6e2ceb9559
   :END:

The statement name can be a string or quoted symbol.

Prepared statements are stored both in the meta slot in the postmodern
connection and in postgresql session information. In the case of prepared
statements generated with defprepared, there is also a lisp function with
the same name.

If you know the prepared statement name, you can delete the prepared statement
from both locations (the default behavior), just from postmodern by passing
:postmodern to the location key parameter or just from postgresql by passing
:postgresql to the location key parameter.

If you pass the name 'All' as the statement name, it will
delete all prepared statements.

The default behavior is to also remove any lisp function of the same name.
This behavior is controlled by the remove-function key parameter.

** function list-postmodern-prepared-statements (&optional (names-only nil))
   :PROPERTIES:
   :ID:       3350ba3c-2389-44d7-af61-a7b2193794f4
   :CUSTOM_ID: b6049a3a-55a2-44be-9dc0-1af2849e2128
   :END:
→ list

List the prepared statements that postmodern has put in the meta slot in the
connection. It will return a list of alists of form:
  ((:NAME . \"SNY24\")
  (:STATEMENT . \"(SELECT name, salary FROM employee WHERE (city = $1))\")
  (:PREPARE-TIME . #<TIMESTAMP 25-11-2018T15:36:43,385>)
  (:PARAMETER-TYPES . \"{text}\") (:FROM-SQL)

If the names-only parameter is set to t, it will only return a list of
the names of the prepared statements.

** function find-postgresql-prepared-statement (name)
   :PROPERTIES:
   :ID:       72bb535d-6a0c-4f59-a00d-fdcb5d84680b
   :CUSTOM_ID: 06ea4b19-3d57-4f08-b92d-d477bf61c456
   :END:
→ string

Returns the specified named prepared statement (if any) that postgresql has for
this session and placed in the meta slot in the connection.

** function find-postmodern-prepared-statement (name)
   :PROPERTIES:
   :ID:       4eb910d7-0fbe-48a2-9002-8075050c937d
   :CUSTOM_ID: b728be40-afaf-45d3-849c-3b7e27b3b0c1
   :END:
→ string

Returns the specified named prepared statement (if any) that postmodern has put
in the meta slot in the connection. Note that this is the statement itself, not
the name.

** function reset-prepared-statement (condition)
   :PROPERTIES:
   :ID:       96e37531-56dd-4580-9fdc-d0e2bb3fbebc
   :CUSTOM_ID: 967c2e66-3ec9-4e07-9de9-1a06d758ac27
   :END:
→ restart

If you have received an invalid-prepared-statement error but the prepared
statement is still in the meta slot in the postmodern connection, this will try
to regenerate the prepared statement at the database connection level and
restart the connection.

** function get-pid ()
   :PROPERTIES:
   :ID:       92d74162-757f-449d-a52a-5c9daa20c5f0
   :CUSTOM_ID: a172b4cb-826f-4bcf-9c50-70676bb7599a
   :END:
→ integer

Get the process id used by postgresql for this connection.

** function get-pid-from-postmodern ()
   :PROPERTIES:
   :ID:       693e7941-c239-406f-8870-566cbb5c9209
   :CUSTOM_ID: b0afcff9-dfa9-466a-a3a2-06b189eac23a
   :END:
→ integer

Get the process id used by postgresql for this connection, but get it from the
postmodern connection parameters.

** function cancel-backend (pid)
   :PROPERTIES:
   :ID:       09b6f356-9e36-4de6-8c74-58331bfea8de
   :CUSTOM_ID: 10b17274-a4d8-4805-adbe-b7386fe28cfb
   :END:

Polite way of terminating a query at the database (as opposed to calling
close-database). This is slower than (terminate-backend pid) and does not
always work.

** function terminate-backend (pid)
   :PROPERTIES:
   :ID:       d8baac2e-115a-485d-b212-02ae397e5117
   :CUSTOM_ID: 203185f5-030c-48e7-8767-e765ac96f8cb
   :END:

Less polite way of terminating at the database (as opposed to calling
close-database). Faster than (cancel-backend pid) and more reliable.
* Database Management
  :PROPERTIES:
  :CUSTOM_ID: database-management
  :END:

** function create-database (database-name &key (encoding "UTF8") (connection-limit -1) owner limit-public-access comment collation template)
   :PROPERTIES:
   :CUSTOM_ID: c3da07c5-73e2-407c-a4cf-155b3ae416b2
   :END:

Creates a basic database. Besides the obvious database-name parameter, you
can also use key parameters to set encoding (defaults to UTF8), owner,
connection-limit (defaults to no limit)). If limit-public-access is set to t,
then only superuser roles or roles with explicit access to this database will
be able to access it. See [[#roles]].

If collation is set, the assumption is that template0 needs to be used as the base
of the database rather than template1 which may contain encoding specific or locale
specific data.
#+BEGIN_SRC lisp
(create-database 'testdb :limit-public-access t
                         :comment "This database is for testing silly theories")
#+END_SRC
** function drop-database (database)
   :PROPERTIES:
   :CUSTOM_ID: database-management
   :END:

Drop the specified database. The database parameter can be a string or a
symbol. Note: Only the owner of a database (or superuser) can drop a database
and there cannot be any current connections to the database.
[[#database-information][See Database information below for information specific functions]
* Database access objects
  :PROPERTIES:
  :ID:       8e7cee8c-f2b9-4569-bf65-e8f3d2f9e31b
  :CUSTOM_ID: daos
  :END:
Postmodern contains a simple system for defining CLOS classes that represent
rows in the database. This is not intended as a full-fledged object-relational
magic system ― while serious ORM systems have their place, they are notoriously
hard to get right, and are outside of the scope of a humble SQL library like
this.

** metaclass dao-class
   :PROPERTIES:
   :ID:       bbf28a59-551a-4805-b2f6-b2d0bd8feaf3
   :CUSTOM_ID: d1d4b5c3-8c21-478e-8ac1-404e4ffdbec5
   :END:
You can work directly with the database or you can use a simple
database-access-class (aka dao) which would cover all the fields in a row.

Postmodern allows you to have a relatively simple but straight forward matching
of clos classes to a database table. At the heart of Postmodern's DAO system is
the dao-class metaclass. It allows you to define classes for your
database-access objects as regular CLOS classes. Some of the slots in these
classes will refer to columns in the database.

To specify that a slot refers to a column, give it a :col-type option containing
an S-SQL type expression (useful if you want to be able to derive a table
definition from the class definition), or simply a :column option with value T.
Such slots can also take a :col-default option, used to provide a database-side
default value as an S-SQL expression. You can use the :col-name initarg (whose
unevaluated value will be passed to to-sql-name) to specify the slot's column's
name.

DAO class definitions support two extra class options: :table-name to give the
name of the table that the class refers to (defaults to the class name),
and :keys to provide a set of primary keys for the table if they have not been
specified in a single column. If more than one key is provided, this creates a
multi-column primary key and all keys must be specified when using operations
such as update-dao and get-dao. When no primary keys are defined, operations
such as update-dao and get-dao will not work.

IMPORTANT: Class finalization for a dao class instance are wrapped with a thread
lock. However, any time you are using threads and a class that inherits from
other classes, you should ensure that classes are finalized before you start
generating threads that create new instances of that class.

The (or db-null integer) form is used to indicate a column can have NULL values
otherwise the column will be treated as NOT NULL.

Simple example:
#+BEGIN_SRC lisp
(defclass users ()
  ((name :col-type string :initarg :name :accessor name)
   (creditcard :col-type (or db-null integer) :initarg :card :col-default :null)
   (score :col-type bigint :col-default 0 :accessor score))
  (:metaclass dao-class)
  (:keys name))
#+END_SRC
In this case the name of the users will be treated as the primary key and the
database table is assumed to be users. (It might be worth noting that "user" is
a reserved word for Postgresql and using reserved words, while possible using
quotes, is generally not worth the additional trouble they cause.)

The name and score slots cannot be null, but the creditcard slot can be null
and actually defaults to null. The :col-default :null specification ensures that
the default in the database for this field is null, but it does not bound the
slot to a default form. Thus, making an instance of the class without
initializing this slot will leave it in an unbound state.

An example of a class where the keys are set as multiple column keys is here:
#+BEGIN_SRC lisp
(defclass points ()
  ((x :col-type integer :initarg :x
      :reader point-x)
   (y :col-type integer :initarg :y
      :reader point-y)
   (value :col-type integer :initarg :value
          :accessor value))
  (:metaclass dao-class)
  (:keys x y))
#+END_SRC

In this case, retrieving a points record would look like the following where
12 and 34 would be the values you are looking to find in the x column and y
column respectively.:

#+BEGIN_SRC lisp
(get-dao 'points 12 34)
#+END_SRC

Now look at a slightly more complex example.
#+BEGIN_SRC lisp
(defclass country ()
  ((id :col-type integer :col-identity t :accessor id)
   (name :col-type string :col-unique t :check (:<> 'name "")
         :initarg :name :reader country-name)
   (inhabitants :col-type integer :initarg :inhabitants
                :accessor country-inhabitants)
   (sovereign :col-type (or db-null string) :initarg :sovereign
              :accessor country-sovereign)
   (region-id :col-type integer :col-references ((regions id))
              :initarg :region-id :accessor region-id))
  (:documentation "Dao class for a countries record.")
  (:metaclass dao-class)
  (:table-name countries))
#+END_SRC
In this example we have an id column which is specified to be an identity column.
Postgresql will automatically generate a sequence of of integers and this will
be the primary key.

We have a name column which is specified as unique and is not null.

We have a region-id column which references the id column in the regions table.
This is a foreign key constraint and Postgresql will not accept inserting a
country into the database unless there is an existing region table with an id
that matches this number. Postgresql will also not allow deleting a region if
there are countries that reference that region's id. If we wanted Postgresql to
delete countries when regions are deleted, that column would be specified as:
#+BEGIN_SRC lisp
   (region-id :col-type integer :col-references ((regions id) :cascade)
     :initarg :region-id :accessor region-id)
#+END_SRC
Now you can see why the double parens.

We also specified that the table name is not "country" but "countries".
(Some style guides recommend that table names be plural and references to rows
be singular.)

When inheriting from DAO classes, a subclass' set of columns also contains all
the columns of its superclasses. The primary key for such a class is the union
of its own keys and all the keys from its superclasses. Classes inheriting from
DAO classes should probably always use the dao-class metaclass themselves.

When a DAO is created with make-instance, the :fetch-defaults keyword argument
can be passed, which, when T, will cause a query to fetch the default values for
all slots that refers to columns with defaults and were not bound through
initargs. In some cases, such as serial and identity columns, which have an
implicit default, this will not work. You can work around this by creating
your own sequence, e.g. "my_sequence", and defining a (:nextval "my_sequence")
default.

Finally, DAO class slots can have an option :ghost t to specify them as ghost
slots. These are selected when retrieving instances, but not written when
updating or inserting, or even included in the table definition. The only known
use for this to date is for creating the table with (oids=true), and specify a
slot like this:
#+BEGIN_SRC lisp
(oid :col-type integer :ghost t :accessor get-oid)
#+END_SRC

** Out of Sync Dao Objects
   :PROPERTIES:
   :CUSTOM_ID: 9027b960-0a1a-4b64-a621-d1d4ab2906f0
   :END:
What Happens when dao classes are out of sync with the database table?
Let's establish our baseline
#+BEGIN_SRC lisp
(defclass test-data ()
    ((id :col-type serial :initarg :id :accessor test-id)
     (a :col-type (or (varchar 100) db-null) :initarg :a :accessor test-a)
     (b :col-type boolean :col-default nil :initarg :b :accessor test-b)
     (c :col-type integer :col-default 0 :initarg :c :accessor test-c)
     (d :col-type numeric :col-default 0.0 :initarg :d :accessor test-d))
    (:metaclass dao-class)
    (:table-name dao-test)
    (:keys id))

#<DAO-CLASS S-SQL-TESTS::TEST-DATA>

(execute (dao-table-definition 'test-data))
#+END_SRC

Now we define a class that uses the same table, but does not have all the columns.
#+BEGIN_SRC lisp
(defclass test-data-short ()
  ((id :col-type serial :initarg :id :accessor test-id)
   (a :col-type (or (varchar 100) db-null) :initarg :a :accessor test-a))
  (:metaclass dao-class)
  (:table-name dao-test)
  (:keys id))
#+END_SRC

We create an instance of the shortened class and try to save it, then
check the results.
#+BEGIN_SRC lisp
(let ((dao (make-instance 'test-data-short :a "first short")))
       (save-dao dao))

(query (:select '* :from 'dao-test) :alists)
(((:ID . 1) (:A . "first short") (:B) (:C . 0) (:D . 0)))
#+END_SRC

It was a successful save, and we see that the missing columns took their
default values.

Now we define a shortened class, but the a slot is now numeric or null
instead of a string and try to save it and check it.
#+BEGIN_SRC lisp
(defclass test-data-short-wrong-1 ()
  ((id :col-type serial :initarg :id :accessor test-id)
   (a :col-type (or numeric db-null) :initarg :a :accessor test-a))
  (:metaclass dao-class)
  (:table-name dao-test)
  (:keys id))

  (let ((dao (make-instance 'test-data-short-wrong-1 :a 12.75)))
       (save-dao dao))

(query (:select '* :from 'dao-test) :alists)

(((:ID . 1) (:A . "first short") (:B) (:C . 0) (:D . 0))
 ((:ID . 2) (:A . "12.75") (:B) (:C . 0) (:D . 0))
#+END_SRC

Notice that the 12.75 has been converted into a string when it was saved.
Postgresql did this automatically. Anything going into a text or varchar
column will be converted to a string.

Now we will go the other way and define a dao with the right number
of columns, but col d is a string when the database expects a numeric
and check that.
#+BEGIN_SRC lisp
(defclass test-data-d-string ()
    ((id :col-type serial :initarg :id :accessor test-id)
     (a :col-type (or (varchar 100) db-null) :initarg :a :accessor test-a)
     (b :col-type boolean :col-default nil :initarg :b :accessor test-b)
     (c :col-type integer :col-default 0 :initarg :c :accessor test-c)
     (d :col-type text :col-default "" :initarg :d :accessor test-d))
    (:metaclass dao-class)
    (:table-name dao-test)
    (:keys id))

  (let ((dao (make-instance 'test-data-d-string :a "D string" :b nil :c 14
                            :d "Trying string")))
       (save-dao dao))

Database error 22P02: invalid input syntax for type numeric: "Trying string"
QUERY: INSERT INTO dao_test (d, c, b, a) VALUES (E'Trying string', 14, false, E'D string') RETURNING id
   [Condition of type DATA-EXCEPTION]

#+END_SRC
Ok. That threw a data exception. What happens if we try to force a numeric into
an integer column?
#+BEGIN_SRC lisp
(let ((dao (make-instance 'test-data-d-string :a "D string" :b nil :c 14.37
                            :d 18.78)))
       (save-dao dao))

Database error 22P02: invalid input syntax for type integer: "14.37"
   [Condition of type CL-POSTGRES-ERROR:DATA-EXCEPTION]

#+END_SRC
Ok. Postgresql is enforcing the types.
#+BEGIN_SRC lisp
(let ((dao (make-instance 'test-data-d-string :a "D string" :b nil :c 14
                            :d 18.78)))
       (save-dao dao))

(query (:select '* :from 'dao-test) :alists)
(((:ID . 1) (:A . "first short") (:B) (:C . 0) (:D . 0))
 ((:ID . 2) (:A . "12.75") (:B) (:C . 0) (:D . 0))
 ((:ID . 3) (:A . "D string") (:B) (:C . 14) (:D . 939/50)))
#+END_SRC

Notice that postmodern returned a ratio 939/50 for the numeric 18.78.

We have looked at saving daos. Now look at returning a dao from the database
where the dao definition is different than the table definition.
First checking to see if we can get a correct dao back.
#+BEGIN_SRC lisp
(get-dao 'test-data 3)
#<TEST-DATA {100C82AA33}>
#+END_SRC
Ok. That worked as expected.

Second using a shortened dao that is correct in type of columns, but
incorrect n the number of columns compared to the database table.
#+BEGIN_SRC lisp
(get-dao 'test-data-short 3)
No slot named b in class TEST-DATA-SHORT. DAO out of sync with table, or
incorrect query used.
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "new-repl-thread" RUNNING {100C205083}>)

#+END_SRC
Not only did it throw an exception, but I needed to actually use an interrupt
from the repl to get back in operation. And then use (reconnect *database*).
Very Bad result.

THIS ERROR IS CONTROLLABLE BY THE VARIABLE *IGNORE-UNKNOWN-COLUMNS*

Now if we setf the default global variable *ignore-unknown-columns* to t
#+BEGIN_SRC lisp
(setf *ignore-unknown-columns* t)

(get-dao 'test-data-short 3)
#<TEST-DATA-SHORT {10054DFED3}>

(describe (get-dao 'test-data-short 3))
#<TEST-DATA-SHORT {100B249783}>
  [standard-object]

Slots with :INSTANCE allocation:
  ID                             = 3
  A                              = "D string"
#+END_SRC
We now have a dao that has fewer slots than the database table it pulled from.
Just to validate that:
#+BEGIN_SRC lisp
(query (:select '* :from 'dao-test :where (:= 'id 3)))

((3 "D string" NIL 14 939/50))
#+END_SRC
Just to be thorough, let's use a dao that has more slots than the database table.
#+BEGIN_SRC lisp
(defclass test-data-long ()
    ((id :col-type serial :initarg :id :accessor test-id)
     (a :col-type (or (varchar 100) db-null) :initarg :a :accessor test-a)
     (b :col-type boolean :col-default nil :initarg :b :accessor test-b)
     (c :col-type integer :col-default 0 :initarg :c :accessor test-c)
     (d :col-type numeric :col-default 0.0 :initarg :d :accessor test-d)
     (e :col-type text :col-default "sell by date" :initarg :e :accessor test-e))
    (:metaclass dao-class)
    (:table-name dao-test)
    (:keys id))
#+END_SRC
Now if we make an instance of this dao and try to save it in the dao-class table:
#+BEGIN_SRC lisp
(let ((dao (make-instance 'test-data-long :a "first short" :d 37.3)))
       (save-dao dao))

Database error 42703: column "e" does not exist
QUERY: INSERT INTO dao_test (d, a)  VALUES ($1, $2) RETURNING e, c, b, id
   [Condition of type CL-POSTGRES-ERROR:UNDEFINED-COLUMN]
#+END_SRC
Postgresql rejected the attempted insert with an undefined column error.
** method dao-keys (class)
   :PROPERTIES:
   :ID:       959682ab-ee0f-4afe-8cf3-38bb5f6de672
   :CUSTOM_ID: b12ed2b8-fc3f-4d3a-ba2a-3c9484d770dc
   :END:
→ list

Returns list of slot names that are the primary key of DAO class. This is likely
interesting if you have primary keys which are composed of more than one slot.
Pay careful attention to situations where the primary key not only has more than
one column, but they are actually in a different order than they are in the
database table itself. You can check this with the internal
find-primary-key-info function. Obviously the table needs to have been defined.
The class must be quoted.
#+BEGIN_SRC lisp
(pomo:find-primary-key-info 'country1)

(("name" "text") ("id" "integer"))
#+END_SRC

** method dao-keys (dao)
   :PROPERTIES:
   :ID:       4fa1fc88-dfb8-433f-90dc-c88e8908a5a8
   :CUSTOM_ID: 34196ad8-c657-4fd0-a475-e2f0b81ff86c
   :END:
→ list

Returns list of values that are the primary key of dao. Explicit keys takes
priority over col-identity which takes priority over col-primary-key.

This is likely interesting if you have primary keys which are composed of
more than one slot. Pay careful attention to situations where the primary key
not only has more than one column, but they are actually in a different order
than they are in the database table itself.  Obviously the table needs to have
been defined. You can provide a quoted class-name or an instance of a dao.

** method find-primary-key-column
→ symbol

Loops through a class's column definitions and returns the first column name
that has bound either col-identity or col-primary-key.

** method dao-exists-p (dao)
   :PROPERTIES:
   :ID:       4a55236e-edfb-4f07-a237-fae3453fc99d
   :CUSTOM_ID: d5835157-a4ba-4bf0-abbd-214b5a90bc80
   :END:
→ boolean

Test whether a row with the same primary key as the given dao exists in the
database. Will also return NIL when any of the key slots in the object are
unbound.

** method make-dao (type &rest args &key &allow-other-keys)
   :PROPERTIES:
   :ID:       a812726c-52ea-4321-9bae-f9646bccc128
   :CUSTOM_ID: 24bce212-b7c3-4526-a869-92c0218f187d
   :END:
→ dao

Combines make-instance with insert-dao. Make the instance of the given class and
insert it into the database, returning the created dao.

** method fetch-defaults (dao)

→ dao if there were unbound slots with default values, otherwise nil

Used to fetch the default values of an object on creation.
An example would be creating a dao object with unbounded slots.
Fetch-defaults could then be used to fetch the default values from the database
and bind the unbound slots which have default values. E.g.
#+BEGIN_SRC lisp
  (let ((dao (make-instance 'test-data :a 23)))
      (pomo:fetch-defaults dao))
#+END_SRC
** method find-primary-key-column (class)

→ symbol

Loops through a class's column definitions and returns
the first column name that has bound either col-identity or col-primary-key.
Returns a symbol.

** macro define-dao-finalization (((dao-name class) &rest keyword-args) &body body)
   :PROPERTIES:
   :ID:       645a03ec-739a-4ee5-b83d-dcbe43ef009a
   :CUSTOM_ID: f7351c36-cb79-43a2-8a5b-5f8aac8ea2d9
   :END:

Create an :around-method for make-dao. The body is executed in a lexical
environment where dao-name is bound to a freshly created and inserted DAO. The
representation of the DAO in the database is then updated to reflect changes
that body might have introduced. Useful for processing values of slots with the
type serial, which are unknown before insert-dao.

** method get-dao (type &rest keys)
   :PROPERTIES:
   :ID:       6dd7dd12-0f9a-4c47-94ee-43f0886df956
   :CUSTOM_ID: 73e62fab-5bfa-4986-b8c4-992e4d0a134b
   :END:
→ dao

Get the single DAO object from the row that has the given primary key values, or NIL
if no such row exists. Objects created by this function will have
initialize-instance called on them (after loading in the values from the
database) without any arguments ― even :default-initargs are skipped. The same
goes for select-dao and query-dao.
#+BEGIN_SRC lisp
(get-dao 'country "The Netherlands")
#<COUNTRY {1010F0DCF3}>
#+END_SRC

From an sql perspective, the standard call to get-dao translates as:
#+BEGIN_SRC sql
select * from table
#+END_SRC

NOTE: if you have added fields to the database table without updating the class
definition, get-dao and select-dao will throw errors. This may cause your
application to appear to hang unless you have the necessary condition handling
in your code. Usually this will only happen during development, so throwing an
error is not a bad idea. If you want to ignore the errors,
set *ignore-unknown-columns* to t.

** macro select-dao (type &optional (test t) &rest sort)
   :PROPERTIES:
   :ID:       8b3533e5-2399-47e4-8fac-5345ec44c878
   :CUSTOM_ID: cd11fa85-5019-4b94-a24c-d0857d633bd2
   :END:
→ list

Select DAO objects for the rows in the associated table for which the given
test (either an S-SQL expression or a string) holds. When sorting arguments are
given, which can also be S-SQL forms or strings, these are used to sort the
result.

(Note that, if you want to sort, you have to pass the test argument.)
#+BEGIN_SRC lisp
(select-dao 'country)
(#<COUNTRY {101088F6F3}> #<COUNTRY {101088FAA3}>)
2

(select-dao 'country (:> 'inhabitants 50000000))
NIL
0

(select-dao 'country (:> 'inhabitants 5000000))
(#<COUNTRY {10108AD293}>)
1

(select-dao 'country (:> 'inhabitants 5000))
(#<COUNTRY {10108CA773}> #<COUNTRY {10108CAB23}>)
2

(select-dao 'country (:> 'inhabitants 5000) 'name) ;sorted by name
(#<COUNTRY {10108EF423}> #<COUNTRY {10108EF643}>)

(mapcar 'country-name (select-dao 'country (:> 'inhabitants 5000) 'name))
("Croatia" "The Netherlands")

(mapcar 'country-name (select-dao 'country (:> 'inhabitants 5000)))
("The Netherlands" "Croatia")
#+END_SRC
If for some reason, you wanted the list in reverse alphabetical order, then:
#+BEGIN_SRC lisp
(select-dao 'country (:> 'id  0) (:desc 'name))
#+END_SRC
** macro do-select-dao (((type type-var) &optional (test t) &rest sort) &body body)
   :PROPERTIES:
   :ID:       b1a7accd-8c3e-429b-a8c8-35f2283855c4
   :CUSTOM_ID: 6273d302-4199-44a0-aa18-3d8f91affd84
   :END:

Like select-dao, but iterates over the results rather than returning them.
For each matching DAO, body is evaluated with type-var bound to the DAO
instance.

Example:
#+BEGIN_SRC lisp
(do-select-dao (('user user) (:> 'score 10000) 'name)
  (pushnew user high-scorers))
#+END_SRC

** macro query-dao (type query &rest args)
   :PROPERTIES:
   :ID:       134f9dcb-0784-461b-a38c-85c14d850910
   :CUSTOM_ID: 6e5766fb-14dd-4f1e-a68a-fd14d781ac9e
   :END:
→ list

Execute the given query (which can be either a string or an S-SQL expression)
and return the result as DAOs of the given type. If the query contains
placeholders ($1, $2, etc) their values can be given as extra arguments. The
names of the fields returned by the query must either match slots in the DAO
class, or be bound through with-column-writers.

** function do-query-dao (((type type-var) query &rest args) &body body)
   :PROPERTIES:
   :ID:       8f5738c2-a11e-4c1b-91bc-b52f62502fbd
   :CUSTOM_ID: 702edc9e-ef43-4df1-9e99-dac6047bdecc
   :END:
→ list

Like query-dao, but iterates over the results rather than returning them.
For each matching DAO, body is evaluated with type-var bound to the instance.

Example:
#+BEGIN_SRC lisp
(do-query-dao (('user user) (:order-by (:select '* :from 'user :where (:> 'score 10000)) 'name))
  (pushnew user high-scorers))
#+END_SRC

** variable *ignore-unknown-columns*
   :PROPERTIES:
   :ID:       a6627d60-61f4-4a9b-86e7-5c1454a4e487
   :CUSTOM_ID: 4a1219dc-d0bc-4fb7-81c9-cb734cb051cc
   :END:

Normally, when get-dao, select-dao, or query-dao finds a column in the database
that's not in the DAO class, it will raise an error. Setting this variable to a
non-NIL will cause it to simply ignore the unknown column.

** method insert-dao (dao)
   :PROPERTIES:
   :ID:       6e534cce-6d6a-4710-875e-bf53aadb2045
   :CUSTOM_ID: 4a83ef48-a40a-423c-a97c-3d6743ce940c
   :END:
→ dao

Insert the given dao into the database. Column slots of the object which are
unbound implies the database defaults. Hence, if these columns has no defaults
defined in the database, the the insertion of the dao will be failed. (This
feature only works on PostgreSQL 8.2 and up.)

** method update-dao (dao)
   :PROPERTIES:
   :ID:       faf45a30-c384-461f-9367-9e7c40c466a5
   :CUSTOM_ID: 08306ea2-4027-40e8-a9df-8bb2fbc63b3e
   :END:
→ dao

Update the representation of the given dao in the database to the values in the
object. This is not defined for tables that do not have any non-primary-key
columns. Raises an error when no row matching the dao exists.

** function save-dao (dao)
   :PROPERTIES:
   :ID:       a61016ef-bf72-4d7f-804f-c4396098833b
   :CUSTOM_ID: 4697a909-970c-492b-b1d6-7e05895f8882
   :END:
→ boolean

Tries to insert the given dao using insert-dao. If the dao has unbound slots,
those slots will be updated and bound by default data triggered by the
database. If this raises a unique key violation error, it tries to update it by
using update-dao instead. In this case, if the dao has unbound slots, updating
will fail with an unbound slots error.

Be aware that there is a possible race condition here ― if some other process
deletes the row at just the right moment, the update fails as well. Returns a
boolean telling you whether a new row was inserted.

This function is unsafe to use inside of a transaction ― when a row with the
given keys already exists, the transaction will be aborted. Use
save-dao/transaction instead in such a situation.

See also: upsert-dao.

** function save-dao/transaction (dao)
   :PROPERTIES:
   :ID:       0162b077-c274-48b0-9d5d-655de2482012
   :CUSTOM_ID: 62a09a7f-8583-404d-b9f3-28b1eb416b0f
   :END:
→ boolean

The transaction safe version of save-dao. Tries to insert the given dao using
insert-dao. If this raises a unique key violation error, it tries to update it
by using update-dao instead. If the dao has unbound slots, updating will fail
with an unbound slots error. If the dao has unbound slots, those slots will be
updated and bound by default data triggered by the database.

Be aware that there is a possible race condition here ― if some other process
deletes the row at just the right moment, the update fails as well. Returns a
boolean telling you whether a new row was inserted.

Acts exactly like save-dao, except that it protects its attempt to insert the
object with a rollback point, so that a failure will not abort the transaction.

See also: upsert-dao.

** method upsert-dao (dao)
   :PROPERTIES:
   :ID:       ab8ea79a-1761-402c-a1bc-3a5c4fd53c24
   :CUSTOM_ID: 8eeaf5dd-a802-4ba0-9983-dc153ffc1dae
   :END:
→ dao

Like save-dao or save-dao/transaction but using a different method that doesn't
involve a database exception. This is safe to use both in and outside a
transaction, though it's advisable to always do it in a transaction to prevent
a race condition. The way it works is:

If the object contains unbound slots, we call insert-dao directly, thus the
behavior is like save-dao.

Otherwise we try to update a record with the same primary key. If the PostgreSQL
returns a non-zero number of rows updated it treated as the record is already
exists in the database, and we stop here.

If the PostgreSQL returns a zero number of rows updated, it treated as the
record does not exist and we call insert-dao.

The race condition might occur at step 3 if there's no transaction: if UPDATE
returns zero number of rows updated and another thread inserts the record at
that moment, the insertion implied by step 3 will fail.

Note, that triggers and rules may affect the number of inserted or updated rows
returned by PostgreSQL, so zero or non-zero number of affected rows may not
actually indicate the existence of record in the database.

This method returns two values: the DAO object and a boolean (T if the object
was inserted, NIL if it was updated).

IMPORTANT: This is not the same as insert on conflict (sometimes called an upsert)
in Postgresq. An upsert in Postgresql terms is an insert with a fallback of updating
the row if the insert key conflicts with an already existing row. An upsert-dao
in Postmodern terms is the reverse. First you try updating an existing object. If
there is no existing object to oupdate, then you insert a new object.

** method delete-dao (dao)
   :PROPERTIES:
   :ID:       f3371904-cd84-4392-a301-0f910bcf1b90
   :CUSTOM_ID: b135af85-b194-4a5c-9c2d-be87f6827877
   :END:

Delete the given dao from the database.

** function dao-table-name (class)
   :PROPERTIES:
   :ID:       718c03fe-5c70-43c1-a986-bc361d1e2ee6
   :CUSTOM_ID: 436e6c77-8550-4462-a956-3affe6d0970c
   :END:
→ string

Get the name of the table associated with the given DAO class (or symbol naming
such a class).

** function dao-table-definition (class)
   :PROPERTIES:
   :ID:       e796fdb5-a8d9-4399-893a-6783dd925e78
   :CUSTOM_ID: 289d7bc0-b4a3-45e3-991b-14b9cfbdcf68
   :END:
→ string

Given a DAO class, or the name of one, this will produce an SQL query string
with a definition of the table. This is just the bare simple definition, so if
you need any extra indices or or constraints, you'll have to write your own
queries to add them, in which case look to s-sql's create-table function.

** macro with-column-writers ((&rest writers) &body body)
   :PROPERTIES:
   :ID:       52b95f7c-f8f0-4e53-8e60-622746f18e16
   :CUSTOM_ID: d8aa15a1-7dfc-47b3-ae14-70626c33bcc3
   :END:

Provides control over the way get-dao, select-dao, and query-dao read values
from the database. This is not commonly needed, but can be used to reduce the
amount of queries a system makes. writers should be a list of alternating column
names (strings or symbols) and writers, where writers are either symbols
referring to a slot in the objects, or functions taking two arguments ― an
instance and a value ― which can be used to somehow store the value in the new
instance. When any DAO-fetching function is called in the body, and columns
matching the given names are encountered in the result, the writers are used
instead of the default behaviour (try and store the value in the slot that
matches the column name).

An example of using this is to add some non-column slots to a DAO class, and use
query-dao within a with-column-writers form to pull in extra information about
the objects, and immediately store it in the new instances.

* Table definition and creation
  :PROPERTIES:
  :ID:       1c0a254a-4a0e-4012-b519-8fe8cbf9ae02
  :CUSTOM_ID: table-definition
  :END:
It can be useful to have the SQL statements needed to build an application's
tables available from the source code, to do things like automatically deploying
a database. The following macro and functions allow you to group sets of SQL
statements under symbols, with some shortcuts for common elements
in table definitions.

** macro deftable (name &body definition)
   :PROPERTIES:
   :ID:       39e40910-e25a-4db4-bd0a-b4b6d1a75630
   :CUSTOM_ID: 16d26863-ae01-49f3-9350-8ea2d5ca363c
   :END:

Define a table. name can be either a symbol or a (symbol string) list. In the
first case, the table name is derived from the symbol's name by S-SQL's rules.
In the second case, the name is given explicitly. The body of definitions can
contain anything that evaluates to a string, as well as S-SQL expressions. The
variables *table-name* and *table-symbol* are bound to the relevant values in
the body. Note that the evaluation of the definition is ordered, so you'll
generally want to create your table first and then define indices on it.

** variable *table-name*
   :PROPERTIES:
   :ID:       3e565b16-153c-4281-8f17-3653e7a9dc5d
   :CUSTOM_ID: d7e145ff-9666-43eb-813d-78a87116532e
   :END:

Used inside deftable to find the name of the table being defined.

** variable *table-symbol*
   :PROPERTIES:
   :ID:       551359a0-8d5b-4d4f-932d-df8759105ee1
   :CUSTOM_ID: 00432de6-10f6-4e52-85d9-6c622e6c37ec
   :END:

Used inside deftable to find the symbol naming the table being defined.

** function !dao-def ()
   :PROPERTIES:
   :ID:       eb1680a7-2a82-4e6a-b31b-aeea22bf7362
   :CUSTOM_ID: 01902b36-20f9-4644-9347-fa6cbead2334
   :END:

Should only be used inside a deftable form. Define this table using the
corresponding DAO class' slots. Adds the result of calling dao-table-definition
on *table-symbol* to the definition.

** function !index (&rest columns), !unique-index (&rest columns)
   :PROPERTIES:
   :ID:       5ceae010-3712-400a-9c8c-0616b8406390
   :CUSTOM_ID: b0e0a7d4-1c23-4ba2-88a4-dac55a3584c8
   :END:

Used inside a deftable form. Define an index on the table being defined. The
columns can be given as symbols or strings.

** function !foreign (target fields &rest target-fields/on-delete/on-update/deferrable/initially-deferred)
   :PROPERTIES:
   :ID:       1378528c-3e7a-452b-8775-b3d84d897ebd
   :CUSTOM_ID: eba9236f-a947-4194-8337-4d0f828f5542
   :END:

Used insde a deftable form. Add a foreign key to the table being defined.
target-table is the referenced table. columns is a list of column names or
single name in this table, and, if the columns have different names in the
referenced table, target-columns must be another list of column names or single
column name of the target-table, or :primary-key to denote the column(s) of the
target-table's primary key as referenced column(s).

The on-delete and on-update arguments can be used to specify ON DELETE and ON
UPDATE actions, as per the keywords allowed in create-table. In addition, the
deferrable and initially-deferred arguments can be used to indicate whether
constraint checking can be deferred until the current transaction completed, and
whether this should be done by default. Note that none of these are
really &key arguments, but rather are picked out of a &rest arg at runtime, so
that they can be specified even when target-columns is not given.

** function !unique (target-fields &key deferrable initially-deferred)
   :PROPERTIES:
   :ID:       c4631db6-9994-40df-97b7-150df71bb121
   :CUSTOM_ID: 5ccbe683-8a43-4373-9371-529a3007bd40
   :END:

Constrains one or more columns to only contain unique (combinations of) values,
with deferrable and initially-deferred defined as in !foreign

** function create-table (symbol)
   :PROPERTIES:
   :ID:       333d4860-6cfe-4009-80f8-a480174d64e1
   :CUSTOM_ID: e1834b87-e348-44ab-9361-0ad1021d1163
   :END:

Takes the name of a dao-class and creates the table identified by symbol by
executing all forms in its definition as found in the *tables* list.

** function create-all-tables ()
   :PROPERTIES:
   :ID:       7477cdc4-59bf-47fb-9b60-25ee9c38eb66
   :CUSTOM_ID: eba2d105-d5c7-49c0-bfed-828e4ff53b09
   :END:

Creates all defined tables.

** function create-package-tables (package)
   :PROPERTIES:
   :ID:       8e36190a-a3a4-4e66-8df4-0a6b6b74f617
   :CUSTOM_ID: a49e80c8-3204-4803-b263-a0cac063ea12
   :END:

Creates all tables identified by symbols interned in the given package.

** variables *table-name*, *table-symbol*
   :PROPERTIES:
   :ID:       25924943-75d9-4612-b2a3-dc94f292c2a5
   :CUSTOM_ID: a932fe23-c677-4bb7-8df8-6dd2adf2beff
   :END:

Used inside deftable to find the name of the table being defined.

Used inside deftable to find the symbol naming the table being defined.

** function drop-table (table-name &key if-exists cascade)
   :PROPERTIES:
   :ID:       0427ecce-416e-4266-a5c7-90e58e22e0b7
   :CUSTOM_ID: f6879b3f-12dc-44a4-b92e-03dbedd0b1cd
   :END:

If a table exists, drop a table. Available additional key parameters
are :if-exists and :cascade.

** Introduction to Multi-table dao class objects
  :PROPERTIES:
  :ID:       e76fc507-bfa6-481b-b429-128ed0ede9e3
  :CUSTOM_ID: 9b329d91-58c8-4153-950f-4e58b71455dc
  :END:

Postmodern's dao-class objects are not required to be tied down to a specific
table. They can be used simply as classes to hold data for whatever purpose your
application may use.

For this introduction, we will use two sets of tables: (1) country-d and
region-d and (2) country-n and region-n. In each case the country table will
have a foreign key tied to a region.

A foreign key is a "constraint" referencing a primary key in another table. The
table containing the foreign key is the referencing or child table and the table
referenced by the foreign key is the referenced or parent table. The foreign key
enforces a requirement that the child table column refering to another table
must refer to a row that exists in the other table. In other words, you cannot
create a row in table country-d that references a region-d name "Transylvania"
if the region-d name "Transylvania" does not yet exist in the region-d table. At
the same time, you could not later delete the region-d row with "Transylvania"
if the country-d row referencing it still exists.

Do you remember the slightly more complicated version of country from earlier on
the page?
#+BEGIN_SRC lisp
(defclass country ()
  ((id :col-type integer :col-identity t :accessor id)
   (name :col-type string :col-unique t :check (:<> 'name "")
         :initarg :name :reader country-name)
   (inhabitants :col-type integer :initarg :inhabitants
                :accessor country-inhabitants)
   (sovereign :col-type (or db-null string) :initarg :sovereign
              :accessor country-sovereign)
   (region-id :col-type integer :col-references ((regions id))
              :initarg :region-id :accessor region-id))
  (:documentation "Dao class for a countries record.")
  (:metaclass dao-class)
  (:table-name countries))
#+END_SRC
That one specified a foreign key reference in the region-id column, so we
cannot insert the data from a country dao unless there is already a region
table with an id column equal to the region-id in the country dao.

Lets look at two slightly different ways of handling countries and regions.

In our first set of tables, country-d will have a region column that references
the name column in a region-d table (so the name column in region-d must be the
primary key for region-d).

This looks relatively straight forward and it is in this simple case. Things
start getting more complicated if you start having to reference a table where
there are many items with the same name. An example would be tracking library
books. There may be multiple copies of a book title, but you need to know which
book was checked out to which library patron. In these types of situations, the
primary key cannot be the name of the region, it needs to reference some
particular id.

In our second set of tables, country-n will have a region-id column that
references an id column in a region-d table (so the id column in region-d must
be the primary key for region-d).

*** Simple Version
   :PROPERTIES:
   :ID:       2758d7e8-ae00-4d01-8c8b-c7ff3a827047
   :CUSTOM_ID: da13ef47-1c9c-4d8e-be07-26a2ffa25fdc
   :END:
Lets start by declaring our classes and we will use the deftable make to create
a definition for our tables that gets stored in the *tables* special variable.
We can then use the (create-table 'class-name) function to create the table in
the database.

Just to be slightly different, we are going to declare the classes without the
:col-reference and :col-unique modifiers and put those into the (deftable) macro
call. We will set the id as a serial in the -d version because we want to use
name as the primary key and seting id as an identity would cause it to be the
primary key.
#+BEGIN_SRC lisp
(defclass region-d ()
  ((id :col-type serial :initarg :id :reader region-id)
   (name :col-type string :initarg :name :accessor region-name))
  (:metaclass pomo:dao-class)
  (:keys name))

(deftable region-d
  (!dao-def)
  (!unique 'name))

(create-table 'region-d)

(defclass country-d ()
  ((id :col-type serial :initarg :id :reader country-id)
   (name :col-type string :initarg :name
         :reader country-name)
   (region-name :col-type string :initarg :region-name :accessor region-name))
   (:metaclass pomo:dao-class)
   (:keys name))

(deftable country-d
  (!dao-def)
  (!unique 'name)
  (!foreign 'region-d 'region-name 'name))

(create-table 'country-d)
#+END_SRC
The new function !foreign insde the deftable adds a foreign key which requires
that a region with that id already exist before you can insert a country.
By the way, because of the foreign key constraint, postgresql will require that
the region-d table be created before the country-d table.

Look at *tables* for a moment:
#+BEGIN_SRC lisp
*tables*
((REGION-D . #<FUNCTION (LAMBDA ()) {534D126B}>)
 (COUNTRY-D . #<FUNCTION (LAMBDA ()) {52A1484B}>))
#+END_SRC
The region-d lambda looks like this:
#+BEGIN_SRC lisp
(LAMBDA ()
    (LET ((*TABLE-NAME* "region_d") (*TABLE-SYMBOL* 'REGION-D))
      (DOLIST (STAT (LIST (!DAO-DEF) (!UNIQUE 'NAME))) (EXECUTE STAT))))
#+END_SRC
The country-d lambda looks like this:
#+BEGIN_SRC lisp
(LAMBDA ()
    (LET ((*TABLE-NAME* "country_d") (*TABLE-SYMBOL* 'COUNTRY-D))
      (DOLIST
          (STAT
           (LIST (!DAO-DEF) (!UNIQUE 'NAME)
                 (!FOREIGN 'REGION-D 'REGION-NAME 'NAME)))
        (EXECUTE STAT))))
#+END_SRC
*** Less Simple Version
   :PROPERTIES:
   :ID:       933f58e1-a4da-4e7f-a227-0fac621e14b0
   :CUSTOM_ID: d8cb7f38-7ef3-4ec2-85a2-b4df7b2c4997
   :END:
In the -n version, we are going to use the id columns as the primary key.
We will not need to tell deftable t
#+BEGIN_SRC lisp
(defclass region-n ()
  ((id :col-type integer :col-identity t :initarg :id :reader region-id)
   (name :col-type string :initarg :name :accessor region-name))
  (:metaclass pomo:dao-class))

(deftable region-n
  (!dao-def)
  (!unique 'name))

(create-table 'region-n)

(defclass country-n ()
  ((id :col-type integer :col-identity t :initarg :id :reader country-id)
   (name :col-type string :initarg :name
         :reader country-name)
   (region-id :col-type integer :initarg :region-id :accessor region-id))
   (:metaclass dao-class))

(deftable country-n
  (!dao-def)
  (!unique 'name)
  (!foreign 'region-n 'region-id 'id))

(create-table 'country-n)
#+END_SRC
How do you find the region-id? While we set the primary key as name for both
country and region in the simple version, it will be a little more work in the
less simple version. Lets start by inserting a couple of regions and we will
stick with the dao method for the moment:
#+BEGIN_SRC lisp
(insert-dao (make-instance 'region-d :name "Western Europe"))
(insert-dao (make-instance 'region-n :name "Western Europe"))
(insert-dao (make-instance 'region-d :name "Southern Europe"))
(insert-dao (make-instance 'region-n :name "Southern Europe"))
#+END_SRC

Now we can add a few countries to country-d:
#+BEGIN_SRC lisp
(insert-dao (make-instance 'country-d :name "The Netherlands"
                                      :region-name "Western Europe"))

(insert-dao (make-instance 'country-d :name "Croatia"
                                      :region-name "Southern Europe"))
#+END_SRC
Now we can add a few countries to country-n, remembering that for this version,
name is not the primary key so how to get the region dao with the name "Western Europe"? For region-d
it is easy because the name is the primary key. So
#+BEGIN_SRC lisp
(get-dao 'region-d "Western Europe")
#<REGION-D {100A322D43}>
#+END_SRC
For region-n it is a little more complicated because the primary key is the id
column, not the name column. So there are a couple of ways to do it. First is
select-dao which will return a list of daos meeting a test criteria, in a sorted
order if that third parameter is also provided. Eg.
#+BEGIN_SRC lisp
(select-dao 'region-n (:= 'id 1))
(#<REGION-N {100AAC6E13}>)

(select-dao 'region-n (:= 'name "Western Europe"))
(#<REGION-N {100A813CF3}>)

(select-dao 'region-n t 'name)
(#<REGION-N {100AC90FA3}> #<REGION-N {100AC911B3}>)
#+END_SRC

Another method with is query-dao, which takes a row and inserts it into a dao.
That gets us a list of daos meeting the select criteria.
#+BEGIN_SRC lisp
(query-dao 'region-n "select * from region_n where name = 'Western Europe'")
(#<REGION {1009E75E63}>)
#+END_SRC
or, using s-sql expression
#+BEGIN_SRC lisp
(query-dao 'region-n (:select '*
                      :from 'region-n
                      :where (:= 'name "Western Europe")))
(#<REGION-D {100A50DA13}>)
#+END_SRC

Here are two different ways of generating the region-id so we can insert a new dao
into country-n:
#+BEGIN_SRC lisp
(insert-dao
  (make-instance 'country-n
                 :name "The Netherlands"
                 :region-id (region-id
                              (first (select-dao 'region-n
                                                 (:= 'name "Western Europe"))))))
#<COUNTRY-N {1002AD79B3}>

(insert-dao
  (make-instance 'country-n
                 :name "Croatia"
                 :region-id (query (:select 'id
                                    :from 'region-n
                                    :where (:= 'name "Southern Europe"))
                             :single)))
#<COUNTRY-N {1002ADE2B3}>
#+END_SRC
But the returned row need not be the result from a single table. Suppose we
create a third table that has population by year and inserted a couple of rows.
This time we will do it with s-sql.
#+BEGIN_SRC lisp
(query (:create-table 'country-population ((id :type bigserial)
                                          (country-id :type integer)
                                          (year :type integer)
                                          (population :type integer))))

(let ((country-id (query (:select 'id
                          :from 'country-d
                          :where (:= 'name "The Netherlands"))
                         :single)))
  (query (:insert-rows-into 'country-population
          :columns 'country-id 'year 'population
          :values `((,country-id 2014 16830000)
                    (,country-id 2015 16900000)
                    (,country-id 2016 16980000)
                    (,country-id 2017 17080000)))))

(let ((country-id (query (:select 'id
                          :from 'country-d
                          :where (:= 'name "Croatia"))
                         :single)))
  (query (:insert-rows-into 'country-population
          :columns 'country-id 'year 'population
          :values `((,country-id 2014 4255518)
                    (,country-id 2015 4232873)
                    (,country-id 2016 4208611)
                    (,country-id 2017 4182846)))))
#+END_SRC
Now we create a class that pulls from all three tables (country, region and
country-population).
#+BEGIN_SRC lisp
(defclass country-with-population ()
  ((country-name :col-type string :initarg :country-name
           :reader country-name)
     (region-name :col-type string :initarg :region-name :accessor region-name)
     (year :col-type integer :initarg :year :reader year)
     (population :col-type integer :initarg :population :reader population))
     (:metaclass dao-class)
     (:keys country-name))
#+END_SRC
Can we use query-dao to get a list of country-with-population daos with the most
recent population data? The answer is yes. That would give us a class that maybe
our application can use without having to worry about constantly going back to
the database to look for the region's name or whatever.

Of course you still need to get the data into the class instances. You could
write the following one time as a function to generate your list of countries
with the most recent population data. Note that you need to rename the columns
to the appropriate initarg name (e.g. 'country-n.name is selected as
'country-name). You do not need to worry about the order of the selected rows.
So long as the selections are renamed properly, the slots will be populated
properly.

In the data that we have in the system, we happen to know that the years
available are the same for every country. In that case, we just want the
information for the maximum year. One way to do that would be:
#+BEGIN_SRC lisp
(query-dao 'country-with-population
                 (:select (:as 'country-n.name 'country-name)
                          'year
                          (:as 'region-n.name 'region-name)
                          'population
                      :from 'country-n
                      :inner-join 'region-n
                      :on (:= 'country-n.region-id 'region-n.id)
                      :inner-join 'country-population
                      :on (:= 'country-n.id 'country-population.country-id)
                      :where (:= 'year (:select (:max 'year)
                                        :from 'country-population))))
#+END_SRC
But what happens if the data is not the same for both countries? Lets drop the
2017 population data row for Croatia and make sure it still returns the most
current year that we have for both countries.
#+BEGIN_SRC lisp
(query (:delete-from 'country-population
        :where (:and (:= 'country-id 2)
                     (:= 'year 2017))))
#+END_SRC
If we run the same query from above, we only get an instance for The Netherlands
because that was the only data available for the maximum year (2017). We need to
approach the data slightly differently.Because this is postmodern and we only
care about the Postgresql database, we can use its DISTINCT ON extension to the
SQL standard.

See https://www.postgresql.org/docs/current/sql-select.html#SQL-DISTINCT
for more documentation.

The following query will pull the most recent year for both countries. How did
that happen? We limited the select clause to distinct country names so we would
only pull one of each country, then ordered the result by country-name, but most
importantly by year descending.
#+BEGIN_SRC lisp
(query-dao 'country-with-population
                 (:order-by (:select  (:as 'country-n.name 'country-name)
                                      'year
                                      (:as 'region-n.name 'region-name)
                                      'population
                             :distinct-on 'country-n.name
                             :from 'country-n
                             :inner-join 'region-n
                             :on (:= 'country-n.region-id 'region-n.id)
                             :inner-join 'country-population
                             :on (:= 'country-n.id
                                     'country-population.country-id))
                     'country-name
                     (:desc 'year)))
(#<COUNTRY-WITH-POPULATION {1009AFAEC3}>
 #<COUNTRY-WITH-POPULATION {1009AFC963}>)
#+END_SRC
At this point you could write a function that gets a country-with-population dao
pulling the most recent population year from the database:
#+BEGIN_SRC lisp
(defun get-country-with-most-recent-population (country)
  (car (query-dao 'country-with-population
                  (:order-by (:select  (:as 'country-n.name 'country-name)
                                       'year
                                       (:as 'region-n.name 'region-name)
                                       'population
                                       :distinct-on 'country-n.name
                                       :from 'country-n
                                       :inner-join 'region-n
                                       :on (:= 'country-n.region-id
                                               'region-n.id)
                                       :inner-join 'country-population
                                       :on (:= 'country-n.id
                                               'country-population.country-id)
                                       :where (:= 'country-n.name '$1))
                             'country-name
                             (:desc 'year))
                  country)))
#+END_SRC
Obviously it is not get-dao, which is simpler but just pulls everything in a
single row from a table and this pulls just the data you want from three
different tables and it is bespoken for that class. Because get-dao is a generic
function, with the normal method being applied when passing a symbol, you could
write a new method for get-dao that would apply if you passed it an actual
country-with-population class instance.

If you want to display fields in a record which matches a dao class that you
have set up, you can call get-dao with the name of table and the primary key.
In this example, the table is "countries and the primary key happens to be the
field "id" with a value of 1.

For example, assume we pull a dao object out of our country-n table for
Croatia:
#+BEGIN_SRC lisp
(describe (get-dao 'country-n 2))
#<COUNTRY-N {1005BF7273}>
  [standard-object]

Slots with :INSTANCE allocation:
  ID                             = 2
  NAME                           = "Croatia"
  REGION-ID                      = 2
#+END_SRC
Notice that the region-id field has an integer value. This works. But assume it
has a slot of region-id, which refers to an id in the table "regions" and you
want the name of the region displayed rather than the region-id. There is a hack
using with-column-writers which essentially writes the name into the link slot.
Now, we write a function that uses the with-column-writers macro and pull in the
actual region name from the regions table.
#+BEGIN_SRC lisp
(defun get-country2 (country-name )
  (first (with-column-writers
         ('region-n 'region-id)
         (query-dao 'country-n
                    (:select 'country-n.* (:as 'region-n.name 'region-n)
                             :from 'country-n
                             :left-join 'region-n
                             :on (:= 'country-n.region-id 'region-n.id)
                             :where (:= 'country-n.name country-name))))))

(describe (get-country2 "Croatia"))
#<COUNTRIES {1003AD23D1}>
  [standard-object]
(describe (get-country2 "Croatia"))
#<COUNTRY-N {100593DF03}>
  [standard-object]

Slots with :INSTANCE allocation:
  ID                             = 2
  NAME                           = "Croatia"
  REGION-ID                      = "Southern Europe"


(region-id (get-country2 "Croatia"))
"Southern Europe"
#+END_SRC

Normally calling the accessor region-id would return an integer, but now it is
returning the name of the region. if you are using the dao as a simple way to
get the relevant data out of the database and you are just going to display
this value, this saves you from having to make additional database calls.
Otherwise, you would have to make an additional call to get the information
from all the foreign tables.

* Roles
  :PROPERTIES:
  :CUSTOM_ID: roles
  :END:
Every connection is specific to a particular database. However, creating roles
or users is global to the entire cluster (the running postgresql server). You
can create policies for any individual database, schema or table, but you need
to ensure that those policies also apply to any subsequently created database,
schema or table. Note that each user is automatically a member of the public
group, so you need to change those policies for public as well.

Per the Postgresql Documentation, CREATE ROLE adds a new role to a PostgreSQL
database cluster. A role is an entity that can own database objects and have
database privileges; a role can be considered a “user”, a “group”, or both
depending on how it is used.
https://www.postgresql.org/docs/current/sql-createrole.html. The only real
difference between "create role" and "create user" is that create user
defaults to having a login attribute and create role defaults to not having
a login attribute.

Often applications will have their own concept of users and the application
will itself have one or more types of roles to which the application user is
assigned. So, for example, the application may have two roles - reader and
editor with which it interacts with postgresql and then there are many
application users registered with the application and probably listed in some
type of user table in postgresql that the application manages. When users 1,2
or 3 log in to the application, the application might connect to the postgresql
cluster using a role that only has read (select) permissions. When users 4 or 5
log in to the application, the applicatin might connect to the postgresql cluster
using a role that has read, insert, update and delete permission. Postmodern
provides a simplified create-role system allowing easy creation of roles that
have readonly, editor or superuser type permissions. Further, those
permissions can be limited to individual databases, schemas or tables.

We suggest that you separate application users from roles. Make it easy to
drop application users. Dropping roles requires going through every database,
reassigning ownership of any objects that role might own or have privileges
on, then dropping ownership of objects, then dropping the role itself.

** function role-exists-p (role-name)
   :PROPERTIES:
   :CUSTOM_ID: 694123c8-957f-4b11-a344-094525d35e7f
   :END:
→ boolean

Does the named role exist in this database cluster? Returns t or nil.
** function create-role
   :PROPERTIES:
   :CUSTOM_ID: 07a9f936-c1b7-4a7d-b5a5-57cd6a24870a
   :END:
(name password &key (base-role :readonly) (schema :public)
                                    (tables :all) (databases :current)
                                    (allow-whitespace nil)
                                    (allow-utf8 nil)
                                    (allow-disallowed-names nil) (comment nil))

Keyword parameters: Base-role. Base-role should be one of :readonly, :editor,
:admin, :standard or :superuser. A readonly user can only select existing data in the
specified tables or databases. An editor has the ability to insert, update,
delete or select data. An admin has all privileges on a database, but cannot
create new databases, roles, or replicate the system. A standard user has no
particular privileges other than connecting to databases.

 :schema defaults to :public but can be a list of schemas. User will not have
access to any schemas not in the list.

 :tables defaults to :all but can be a list of tables. User will not have access
to any tables not in the list.

 :databases defaults to :current but can be a list of databases. User will not
have access to any databases not in the list.

 :allow-whitespace - Whitespace in either the name or password is not allowed by
default.

 :allow-utf8 defaults to nil. If t, the name and password will be normalized. If
nil, the name and password are limited to printable ascii characters. For fun
reading on utf8 user names see
https://labs.spotify.com/2013/06/18/creative-usernames. Also interesting reading
is https://github.com/flurdy/bad_usernames and https://github.com/dsignr/disallowed-usernames/blob/master/disallowed%20usernames.csv,
and https://www.b-list.org/weblog/2018/feb/11/usernames/

 :allow-disallowed-names defaults to nil. If nil, the user name will be checked
against *disallowed-role-names*.

 As an aside, if allowing utf8 in names, you might want to think about whether
you should second copy of the username in the original casing and normalized as
NFC for display purposes as opposed to normalizing to NFKC. It might be viewed
as culturally insensitive to change the display of the name.
** function drop-role (role-name &optional (new-owner "postgres") (database :all))
   :PROPERTIES:
   :CUSTOM_ID: e527824a-811e-41fa-ae49-2dd24f436ed3
   :END:
→ boolean

The role-name and optional new-owner name should be strings. If they are
symbols, they will be converted to string and hyphens will be converted to
underscores.

Before dropping the role, you must drop all the objects it owns (or reassign
their ownership) and revoke any privileges the role has been granted on other
objects. If database is :all, drop-role will loop through all databases in
the cluster ensuring that the role has no privileges or owned objects in
every database. Otherwise drop-role will drop objects owned by a role in the
current database.

We will reassign ownership of the objects to the postgres role
unless otherwise specified in the optional second parameter. Returns t if
successful. Will not drop the postgres role.
** function alter-role-search-path (role search-path)
   :PROPERTIES:
   :CUSTOM_ID: 20f2425f-6a17-46b0-a8b7-22843a7f11e1
   :END:

Changes the priority of where a role looks for tables (which schema first,
second, etc. Role should be a string or symbol. Search-path could be a list of schema
names either as strings or symbols.
** function change-password (role password &optional expiration-date)
   :PROPERTIES:
   :CUSTOM_ID: 08c10e1f-96a3-4f3b-8b9c-f4a0251d43cd
   :END:

Alters a role's password. If the optional expiration-date parameter is provided,
the password will expire at the stated date. A sample expiration date would be
'December 31, 2020'. If the expiration date is 'infinity', it will never expire.
The password will be encrypted in the system catalogs. This is
automatic with postgresql versions 10 and above.

** function grant-role-permissions (role-type name &key (schema :public) (tables :all) (databases :all))
   :PROPERTIES:
   :CUSTOM_ID: 41e66f79-aa57-4f00-b218-5f1a85c7d970
   :END:

Grant-role-permissions assumes that a role has already been created, but
permissions need to be granted or revoked on a particular database.

   A  :superuser can create databases, roles, replication, etc. Returns nil.
   A  :standard user has no particular privileges or restrictions. Returns nil.
   An :admin user can edit existing data, insert new data and create new tables
in the specified databases/schemas/tables.
   An :editor user can update fields or insert new records but cannot create new
tables in the specified tables or databases.
   A  :readonly role can only read existing data in the specified schemas,
tables or databases. Schema, tables or databases can be :all or a list of
schemas, tables or databases to be granted permission.

  Granting :all provides access to all future items of that type as well.

  Note that the schema and table rights and revocations granted are limited to
the connected database at the time of execution of this function.
** function grant-readonly-permissions (schema-name role-name &optional (table-name nil))
   :PROPERTIES:
   :CUSTOM_ID: ac447228-8f95-4a30-840d-10a1a9a418f4
   :END:

Grants select privileges to a role for the named schema. If the optional
table-name parameter is provided, the privileges are only granted with respect
to that table. Note that we are giving some function execute permissions if
table-name is nil, but if the table-name is specified, those are not provided.
Your mileage may vary on how many privileges you want to provide to a
read-only role with access to only a limited number of tables.
** function grant-editor-permissions (schema-name role-name &optional (table-name nil))
   :PROPERTIES:
   :CUSTOM_ID: 1a271dc1-5e76-4b90-84d5-423a24059e8b
   :END:

Grants select, insert, update and delete privileges to a role for the named
schema. If the optional table-name parameter is provided, the privileges are only
granted with respect to that table. Note that we are giving some function execute
permissions if table-name is nil, but if the table-name is specified, those are
not provided. Your mileage may vary on how many privileges you want to provide
to a editor role with access to only a limited number of tables.
** function grant-admin-permissions (schema-name role-name &optional (table-name nil))
   :PROPERTIES:
   :CUSTOM_ID: 4ac88ea3-bf89-462b-a9dd-cfa115234fb3
   :END:

Grants all privileges to a role for the named schema. If the optional table-name
parameter is provided, the privileges are only granted with respect to that table.
** function revoke-all-on-table (table-name role-name)
   :PROPERTIES:
   :CUSTOM_ID: 6e7e67b0-0fb1-461e-a842-a6e6c59f4c2f
   :END:

Takes a table-name which could be a string, symbol or list of strings or
symbols of tables names, a role name and revokes all privileges that
role-name may have with that/those tables. This is limited to the currently
connected database and can only revoke the privileges granted by the caller
of the function.
** function list-role-accessible-databases (role-name)
   :PROPERTIES:
   :CUSTOM_ID: 77975516-0416-428c-a9c8-6655b5aebedd
   :END:
→ list

Returns a list of the databases to which the specified role can connect.
** function list-roles (&optional (lt nil))
   :PROPERTIES:
   :ID:       e6d13898-e158-4001-b54c-cc7e58342023
   :CUSTOM_ID: a5bdaaca-11e5-438d-83a8-495cef9b85fa
   :END:
→ list

Returns a list of alists of rolenames, role attributes and membership in roles.
See https://www.postgresql.org/docs/current/role-membership.html for an
explanation. Optionally passing :alists or :plists can be used to set the return
list types to :alists or :plists. This is the same as the psql function \du.

** function list-role-permissions (&optional role)
   :PROPERTIES:
   :CUSTOM_ID: fd161f71-a334-4959-8b42-dda5271ef6d5
   :END:
→ list

This returns a list of sublists of the permissions granted  within the
currently connected database. If an optional role is provided, the result is
limited to that role. The sublist returned will be in the form of role-name,
schema-name, table-name and then a string containing all the rights of that role
on that table in that schema.
* Database Information
  :PROPERTIES:
  :ID:       ecc7ca5e-9117-488b-aa7c-011d56409f76
  :CUSTOM_ID: database-information
  :END:
** function add-comment (type name comment &optional (second-name ""))
   :PROPERTIES:
   :CUSTOM_ID: 22c6eb1c-c0ca-44fc-a8f1-590fda047866
   :END:

Attempts to add a comment to a particular database object. The first parameter is a keyword for the type of database object. The second parameter is the name of the object. The third parameter is the comment itself. Some objects require an additional identifier. The names can be strings or symbols.

Example usage would be:
#+BEGIN_SRC lisp
 (add-comment :database 'my-database-name "Does anyone actually use this database?")

 (add-comment :column 'country-locations.name "Is what it looks like - the name of a country")

 (add-comment :column "country_locations.name" "Is what it looks like - the name of a country")
#+END_SRC

Example usage where two identifiers are required would be constraints:
#+BEGIN_SRC lisp
 (add-comment :constraint 'constraint1  "Some kind of constraint descriptions here"
              'country-locations)
#+END_SRC

** function get-database-comment (database-name)
   :PROPERTIES:
   :CUSTOM_ID: d993f27b-95d6-4a5b-bdf3-3e06beed0213
   :END:
→ string

Returns the comment, if any, attached to a database.
** function postgresql-version ()
   :PROPERTIES:
   :ID:       9243f0ff-2001-4427-8cf9-33f9a9b6fd5c
   :CUSTOM_ID: 29d56bfd-15a0-40bb-b7f1-a1683b392695
   :END:
→ string

Returns the version string provided by postgresql of the current postgresql
server. E.g. "PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by gcc
(Arch Linux 9.3.0-1) 9.3.0, 64-bit". If you want just the postgresql version
number, use (cl-postgres:get-postgresql-version).

** function database-version ()
   :PROPERTIES:
   :ID:       9243f0ff-2001-4427-8cf9-33f9a9b6fd5c
   :CUSTOM_ID: 29d56bfd-15a0-40bb-b7f1-a1683b392695
   :END:
→ string

DEPRECATED. This returns the postgresql server version number, not a version
number from the currently connected database. The format of the return string
is determined by the current postgresql server.
E.g. "PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by gcc
(Arch Linux 9.3.0-1) 9.3.0, 64-bit".

If you want just the postgresql version
number, use (cl-postgres:get-postgresql-version).

** function current-database ()
   :PROPERTIES:
   :ID:       4928edd1-e74c-4e90-92d8-bd9b98ab0894
   :CUSTOM_ID: 69269619-9b8a-4e88-8ede-777182579d0a
   :END:
→ string

Returns the string name of the current database.

** function database-exists-p (database-name)
   :PROPERTIES:
   :ID:       96e0c18f-4a1e-4cc5-b9c6-5bcd368d0d13
   :CUSTOM_ID: 03fec9c2-6282-4b33-abf8-4db16044cf52
   :END:
→ boolean

Checks to see if a particular database exists. Returns T if true, nil if not.

** function database-size (&optional database-name)
   :PROPERTIES:
   :ID:       9afb5a1e-ef10-4d54-91be-b30debc708dd
   :CUSTOM_ID: d8827c9d-64ff-4334-9a14-1ca4536f8d0a
   :END:
→ list

Given the name of a database, will return the name, a pretty-print string of
the size of the database and the size in bytes. If a database name is not
provided, it will return the result for the currently connected database.

** function num-records-in-database ()
   :PROPERTIES:
   :ID:       2893eb67-97ae-41cb-8987-1924855ec48a
   :CUSTOM_ID: 25b5233f-9a2c-4e39-8902-4a0b88e3b5b3
   :END:
→ list

Returns a list of lists with schema, table name and approximate number of
records in the currently connected database.

** function list-databases (&key (order-by-size nil) (size t))
   :PROPERTIES:
   :ID:       a47beb6b-fdbd-470b-ad85-541d0e6518f8
   :CUSTOM_ID: b5909c41-f24b-4678-8bd9-759d543c4d81
   :END:
→ list

Returns a list of lists where each sub-list contains the name of the database,
a pretty-print string of the size of that database and the size in bytes. The
default order is by database name. Pass t as a parameter to :order-by-size
for order by size. Setting size to nil will return just the database names
in a single list ordered by name. This function excludes the template databases

** function list-database-functions ()
   :PROPERTIES:
   :ID:       61f0e7e5-cf5d-4c2e-967d-588808d1a1bc
   :CUSTOM_ID: ff1d636e-12ba-4fb0-8513-7f808617b956
   :END:
→ list

Returns a list of the functions in the database from the information_schema.


DEPRECATED FOR DESCRIBE-TRIGGERS. List detailed information on the triggers from
the information_schema table.
** function list-database-users ()
   :PROPERTIES:
   :ID:       adfb5355-fd04-4835-a2bd-337dc9402915
   :CUSTOM_ID: 5810bfc5-9338-4a6b-807f-bc72265771a0
   :END:
→ list

List database users (actually 'roles' in Postgresql terminology).
** function list-database-access-rights (&optional database-name)
   :PROPERTIES:
   :CUSTOM_ID: 36e580f9-d647-4f6d-869b-0fcd347fb9d5
   :END:
→ list

If the database parameter is specifed, this returns an list of lists where
each sublist is a role name and whether they have access rights (t or nil) to that
particular database. If the database-name is not provided, the sublist is
a database name, a role name and whether they have access rights (t or nil). This
excludes the template databases.

** function list-available-types ()
   :PROPERTIES:
   :ID:       b5ebabe7-31f9-45b6-8ecb-6035febaa392
   :CUSTOM_ID: 3aeac559-710e-4f60-b687-33b25a6f575a
   :END:
→ list

List the available data types in the connected postgresql version, It returns a
list of lists, each sublist containing the oid (object identifier number) and
the name of the data types. E.g. (21 "smallint")

** function list-available-collations ()
   :PROPERTIES:
   :CUSTOM_ID: da41c0fb-9479-4e23-bdf2-ba73db959e36
   :END:
→ list

Get a list of the collations available from the current database cluster.
Collations are a mess as different operating systems provide different
collations. We might get some sanity if Postgresql can use ICU as the default.
See https://wiki.postgresql.org/wiki/Collations.
** function list-available-extensions ()
   :PROPERTIES:
   :ID:       353cafc2-ca5c-4197-b820-3662dbbea2e3
   :CUSTOM_ID: f6a3893a-0d39-4484-9d3d-40d0ba2e05fd
   :END:
→ list

List the postgresql extensions which are available in the system to the
currently connected database. The extensions may or may not be installed.
** function list-installed-extensions ()
   :PROPERTIES:
   :ID:       922fca24-53d7-4883-844a-cf383ffc7322
   :CUSTOM_ID: 2855d5f5-3957-49ba-9d07-f61464e6da28
   :END:
→ list

List the postgresql extensions which are installed in the currently connected
database.
** function list-templates ()
   :PROPERTIES:
   :CUSTOM_ID: 5bc847be-5de4-4e64-8feb-7256f58b1a0a
   :END:
→ list

Returns a list of existing database template names.
** function change-toplevel-database (new-database user password host)
   :PROPERTIES:
   :ID:       6d41d3c5-2013-4404-aae6-2a7cd5df4b18
   :CUSTOM_ID: e0ce24b7-5619-4ab7-9912-48ebfca4605f
   :END:
→ string

Just changes the database assuming you are using a toplevel connection.
Recommended only for development work. Returns the name of the newly connected
database as a string.

** function cache-hit-ratio ()
   :PROPERTIES:
   :ID:       4d405778-1b17-4928-8d40-e239f8d4c73d
   :CUSTOM_ID: 932d1dde-71e2-4f26-bac4-17a238101e24
   :END:
→ list

The cache hit ratio shows data on serving the data from memory compared to how
often you have to go to disk. This function returns a list of heapblocks read
from disk, heapblocks hit from memory and the ratio of heapblocks hit from
memory / total heapblocks hit. Borrowed from: https://www.citusdata.com/blog/2019/03/29/health-checks-for-your-postgres-database/

** function bloat-measurement ()
   :PROPERTIES:
   :ID:       1d81081b-3cfe-4ef5-989f-23c5ed44d7fc
   :CUSTOM_ID: 84bc40e4-44bf-4c1e-91d2-b32ba77f86c4
   :END:
→ list

Bloat measurement of unvacuumed dead tuples.
Borrowed from: https://www.citusdata.com/blog/2019/03/29/health-checks-for-your-postgres-database/ who
borrowed it from https://github.com/heroku/heroku-pg-extras/tree/master/commands.

** function unused-indexes ()
   :PROPERTIES:
   :ID:       cdbc1e43-b4a7-4709-89f7-d93ba7ac3bae
   :CUSTOM_ID: 10ec1cf5-e865-43e9-a093-8f27916af0d2
   :END:
→ list

Returns a list of lists showing schema.table, indexname, index_size and number
of scans. The code was borrowed from: https://www.citusdata.com/blog/2019/03/29/health-checks-for-your-postgres-database/

** function check-query-performance (&optional (ob nil) (num-calls 100) (limit 20))
   :PROPERTIES:
   :ID:       31ab040b-01fb-4a08-8c27-4b3bc35c9361
   :CUSTOM_ID: c532268f-61d7-4613-85cc-460d7d92aab0
   :END:
→ list

This function requires that postgresql extension pg_stat_statements must be
loaded via shared_preload_libraries. It is borrowed from https://www.citusdata.com/blog/2019/03/29/health-checks-for-your-postgres-database/.
Optional parameters:

 OB allow order-by to be 'calls', 'total-time', 'rows-per'
or 'time-per', defaulting to time-per.

num-calls to require that the number of calls exceeds a certain threshold, and
limit to limit the number of rows returned. It returns a list of lists, each
row containing the query, number of calls, total_time, total_time/calls,
stddev_time, rows, rows/calls and the cache hit percentage.

* Constraints
  :PROPERTIES:
  :ID:       b857f2fe-7b5c-4b13-9909-cb637f7ba367
  :CUSTOM_ID: constraints
  :END:
** function list-unique-or-primary-constraints (table-name)
   :PROPERTIES:
   :ID:       e5adb03e-a26a-40fa-bde2-05f541fc70cf
   :CUSTOM_ID: e20d9e5c-b0a7-44a6-8907-ad205ec1e0b8
   :END:
→ list

List constraints on a table. Table-name can be either a string or quoted. Turns
constraints into keywords if strings-p is not true.

** function list-all-constraints (table-name)
   :PROPERTIES:
   :ID:       d641e79f-b66f-4248-9c1a-284f07182d12
   :CUSTOM_ID: 4b8a62cb-647b-4c3b-b2a7-58476fff58d1
   :END:
→ list

Users information_schema to list all the constraints in a table. Table-name can
be either a string or quoted. Turns constraints into keywords if strings-p is
not true.

** function describe-constraint (table-name constraint-name)
   :PROPERTIES:
   :ID:       8d6cff99-a479-4b98-9fd5-fd77517b61b4
   :CUSTOM_ID: 4f692c41-549f-462d-b98c-a8f7e400f4cc
   :END:
→ list

Return a list of alists of the descriptions a particular constraint given the
table-name and the constraint name using the information_schema table.

** function describe-foreign-key-constraints ()
   :PROPERTIES:
   :ID:       96f4c221-be13-440d-a7ac-0b446bfb06cc
   :CUSTOM_ID: dfe5a61e-7450-47b7-a17b-0d9bd83e1706
   :END:
→ list

Generates a list of lists of information on the foreign key constraints
* Indexes/Indices
  :PROPERTIES:
  :ID:       a265f57e-3928-4386-92c0-ab2764f4fdc5
  :CUSTOM_ID: indexes
  :END:
** function create-index (name  &key unique if-not-exists concurrently on using fields)
   :PROPERTIES:
   :ID:       8724742c-e2fe-48f5-b190-7c1218f9995d
   :CUSTOM_ID: 21392a30-a33c-4330-9a96-abaebcc0af66
   :END:

Create an index. Slightly less sophisticated than the query version because it
does not have a where clause capability.

** function drop-index (name &key concurrently if-exists cascade)
   :PROPERTIES:
   :ID:       9a3553c3-9d58-490f-93e3-2d04b5bd72bc
   :CUSTOM_ID: 6bfcf7a6-6c14-4fad-82f4-5be599f1466b
   :END:

Drop an index. Available keys are :concurrently, :if-exists, and :cascade.

** function list-indices (&optional strings-p)
   :PROPERTIES:
   :ID:       e7fa9796-6804-4446-bfda-3455432d4453
   :CUSTOM_ID: 42f1ee95-201b-4d66-b02e-1b35b0e1614c
   :END:
→ list

Return a list of the indexs in a database. Turn them into keywords if strings-p
is not true.

** function list-table-indices (table-name &optional strings-p)
   :PROPERTIES:
   :ID:       d57a9331-04b4-4920-9fe5-36d4b1d785bb
   :CUSTOM_ID: 72f27f96-392f-4f33-a152-e15888a98c5d
   :END:
→ list

List the index names and the related columns in a single table. Each index will
be in a separate sublist.

** function index-exists-p (name)
   :PROPERTIES:
   :ID:       82c1851f-91cc-4e4d-b802-b2ba37ec6938
   :CUSTOM_ID: c01dc7a8-0153-4857-acad-cb7ec8eccbdc
   :END:
→ boolean

Tests whether an index with the given name exists. The name can be either a
string or a symbol.

** function list-indexed-column-and-attributes (table-name)
   :PROPERTIES:
   :ID:       47908329-5309-4319-9c16-56821f4b6233
   :CUSTOM_ID: 07e4d320-8201-4cc5-803d-c83ee681d103
   :END:
→ list

List the indexed columns and their attributes in a table. Includes primary
key.

** function list-index-definitions (table-name)
   :PROPERTIES:
   :ID:       0078a757-8cc5-46a7-956e-ddb1fe2c579b
   :CUSTOM_ID: 56922f26-5ab4-4c1a-98a2-a0ab56eff9bb
   :END:
→ list

Returns a list of the definitions used to create the current indexes for
the table

* Keys
  :PROPERTIES:
  :ID:       342fdfce-eed8-4ed1-a208-37c417b5a291
  :CUSTOM_ID: keys
  :END:
** function find-primary-key-info (table-name &optional (just-key nil))
   :PROPERTIES:
   :ID:       87a5e1c4-fe1b-4b9a-bdcf-7dbe62bd20f1
   :CUSTOM_ID: 5bf78e17-6506-4f49-b103-9900978f8344
   :END:
→ list

Returns a list of sublists where the sublist contains two strings. If a table
primary key consists of only one column, such as 'id' there will be a single
sublist where the first string is the name of the column and the second string
is the string name for the datatype for that column. If the primary key for the
table consists of more than one column, there will be a sublist for each column
subpart of the key. The sublists will be in the order they are used in the key,
not in the order they appear in the table. If just-key is set to t, the list
being returned will contain just the column names in the primary key as string
names with no sublists. If the table is not in the public schema, provide the
fully qualified table name e.g. schema-name.table-name.

** function list-foreign-keys (table-name)
   :PROPERTIES:
   :ID:       cb0a151a-ad44-4a7a-896d-47903d0e718b
   :CUSTOM_ID: 68d136c2-a216-4def-87f9-726f72dda631
   :END:
→ list

Returns a list of sublists of foreign key info in the form of
   '((constraint-name local-table local-table-column
     foreign-table-name foreign-column-name))

* Schema/Schemata
  :PROPERTIES:
  :ID:       eef5ba67-cfe2-47dc-b432-2a75b45765d8
  :CUSTOM_ID: schema
  :END:
Schema allow you to separate tables into differnet name spaces. In different
schemata two tables with the same name are allowed to exists. The tables can
be referred by fully qualified names or with the macro with-schema. You could
also set the search path with set-search-path. For listing end checking there
are also the functions list-schemata and schema-exist-p. The following
functions allow you to create, drop schemata and to set the search path.

** macro with-schema ((namespace &key :strict t :if-not-exist :create :drop-after) &body body)
   :PROPERTIES:
   :ID:       70159647-6efd-4fcc-acf0-86b24594822b
   :CUSTOM_ID: 9b1b791c-5e04-4512-91cb-9b44fac7b76e
   :END:

A macro to set the schema search path (namespace) of the postgresql database to
include as first entry a specified schema and then executes the body. Before
executing body the PostgreSQL's session variable search_path is set to the given
namespace. After executing body the search_path variable is restored to the
original value.

   Calling with :strict 't only the specified schema is set as current search
path. All other schema are then not searched any more. If strict is nil, the
namespace is just first schema on the search path upon the the body execution.

   Calling with :if-not-exist set to :create the schema is created if this
schema did not exist.

   Calling with :if-not-exist set to nil, an error is signaled.

   calling with drop-after set to 't the schema is removed after the execution
of the body form.

   example :
     (with-schema (:schema-name :strict nil :drop-after nil :if-not-exist :error)
            (foo 1)
            (foo 2))

   example :
     (with-schema ('uniq :if-not-exist :create) ;; changing the search path
            (schema-exists-p 'uniq))

** function list-schemata ()
   :PROPERTIES:
   :ID:       8fa081ea-d959-457d-89ae-980bbb997148
   :CUSTOM_ID: cb98d8fa-8750-4d3c-b7c2-a060205609d6
   :END:
→ list

List all existing user defined schemata.

Note: The query uses the portable information_schema relations instead of
pg_tables relations.
#+BEGIN_SRC sql
select schema_name
from information_schema.schemata
where schema_name !~ '(pg_*)|information_schema'
order by schema_name ;
#+END_SRC

** function list-schemas ()
   :PROPERTIES:
   :ID:       06eff6ed-5de0-4947-9dd1-26ae7dedd360
   :CUSTOM_ID: 612d3bfd-36e2-4b27-a3e9-9f4e4cf15428
   :END:
→ list

List schemas in the current database, excluding the pg_* system schemas.

** function schema-exists-p (schema)
   :PROPERTIES:
   :ID:       f52064e9-e859-416e-bb67-20f5de49613e
   :CUSTOM_ID: a8a3a0df-edf5-4f17-bb97-a3d76973d078
   :END:
→ boolean

Tests the existence of a given schema. Returns T if the schema exists or NIL
otherwise. The name provided can be either a string or quoted symbol.

** function create-schema (schema)
   :PROPERTIES:
   :ID:       3d4619fa-faef-47b2-b6ab-61b36e8b52b2
   :CUSTOM_ID: 06e76060-e646-4fe8-b1b3-142afb2e370b
   :END:

Creates a new schema. Raises an error if the schema is already exists.

** function drop-schema (schema &key (if-exists nil) (cascade nil))
   :PROPERTIES:
   :ID:       cc7fe0f4-31b5-435c-9b8d-22564f7e0ad5
   :CUSTOM_ID: 79d7fdbb-54d7-48e1-821d-9379e3940577
   :END:

Drops an existing database schema. Accepts :if-exists and/or :cascade arguments
like :drop-table. A notice instead of an error is raised with the is-exists
parameter.

** function get-search-path ()
   :PROPERTIES:
   :ID:       639f826f-aed2-4a2d-811c-fe862953d195
   :CUSTOM_ID: b8999d95-0ef5-492e-af5b-cfbdc91278e6
   :END:

Returns the default schema search path for the current session.

** function set-search-path (path)
   :PROPERTIES:
   :ID:       1fa0b1a6-af88-4083-b3f1-16b8b79aca3c
   :CUSTOM_ID: 125a3594-080f-40eb-997d-d7ef927420e6
   :END:

This changes the postgresql runtime parameter controlling what order schemas are
searched. You can always use fully qualified names [schema.table]. By default,
this function only changes the search path for the current session. This
function is used by with-schema.
** function split-fully-qualified-tablename (name)
   :PROPERTIES:
   :ID:       1aa410f7-b60b-4c95-bc4e-dacefe8cc04c
   :CUSTOM_ID: cfacd9fe-b640-4aee-985b-149f4b9ce930
   :END:
→ list
Take a tablename of the form database.schema.table or schema.table or table and
return the tablename and the schema name. The name can be a symbol or a string.
Returns a list of form '(table schema database. If the tablename is not fully
qualified, it will assume that the schema should be \"public\".

* Sequences
  :PROPERTIES:
  :ID:       62e4d0bd-e12f-47c6-8373-a174a7d8d7b1
  :CUSTOM_ID: sequences
  :END:
** function create-sequence (name &key temp if-not-exists increment min-value max-value start cache)
   :PROPERTIES:
   :ID:       37802810-069f-4219-a36a-1e4f754dd5f8
   :CUSTOM_ID: 4d295beb-7a6d-402e-a831-00db88584cb4
   :END:

  Create a sequence. Available additional key parameters
are :temp :if-not-exists :increment :min-value :max-value :start and :cache. See
https://www.postgresql.org/docs/current/static/sql-createsequence.html for
details on usage.

** function sequence-next (sequence)
   :PROPERTIES:
   :ID:       3001c5dd-da96-4263-b427-c04368e8cf41
   :CUSTOM_ID: 47336489-34f5-401b-be21-2d7cb0b47e85
   :END:
→ integer

Shortcut for getting the next value from a sequence. The sequence identifier can
be either a string or a symbol, in the latter case it will be converted to a
string according to S-SQL rules.

** function drop-sequence (name &key if-exists cascade)
   :PROPERTIES:
   :ID:       1998fd52-d0e1-439b-9cfa-d3f72c8a3609
   :CUSTOM_ID: e316b343-ad9c-4610-b074-0d554e4b63ed
   :END:
→ list

Drop a sequence. Name should be quoted. Available key parameters are :if-exists
and :cascade.

** function list-sequences (&optional strings-p)
   :PROPERTIES:
   :ID:       8f8b89c8-9d01-460f-b60f-020e8658bbe7
   :CUSTOM_ID: 320f409d-dfc2-4145-b106-0e642b21fa95
   :END:
→ list

Returns a list of the sequences in the current database. When strings-p is T,
the names will be given as strings, otherwise as keywords.

** function sequence-exists-p (name)
   :PROPERTIES:
   :ID:       e64dd37f-81c2-43f8-88fe-8444771b7631
   :CUSTOM_ID: da78ff64-0fb8-41a7-b17e-1f24ec8abe63
   :END:
→ boolean

Tests  whether a sequence with the given name exists. The name can be either a
string or a symbol.

* Tables
  :PROPERTIES:
  :ID:       5a351917-b940-4c94-a3dc-2795f9a76211
  :CUSTOM_ID: tables
  :END:
** function list-tables (&optional strings-p)
   :PROPERTIES:
   :ID:       bd228cd6-3651-48ca-a9c5-a27737fbaacc
   :CUSTOM_ID: ba11f8df-3297-4720-a267-02896b49575a
   :END:
→ list

DEPRECATED FOR LIST-ALL-TABLES. Return a list of the tables in the public schema
of a database. By default the table names are returned as keywords. They will be
returned as lowercase strings if strings-p is true.

** function list-all-tables (&optional (fully-qualified-names-only nil))
   :PROPERTIES:
   :CUSTOM_ID: ad67dcb1-7123-47dc-9402-e5adcecc7e6a
   :END:

   :PROPERTIES:
   :ID:       bd228cd6-3651-48ca-a9c5-a27737fbaacc
   :END:
→ list

If fully-qualified-names-only is set to t, returns a flattened list of all
schema.table names other than pg_catalog or the information_schema.

Otherwise returns the following info:

schema-name, table-name, table-owner, tablespace, hasindexes, hasrules, hastriggers
and rowsecurity(&optional strings-p).

** function list-tables-in-schema (&optional (schema-name "public") (strings-p nil))
   :PROPERTIES:
   :ID:       6e7c1873-ad5b-4cd0-9389-b6389cb7ea05
   :CUSTOM_ID: 37cd0ae4-b9b2-4776-a58e-dc396e639161
   :END:
→ list

Returns a list of tables in a particular schema, defaulting to public. If
schema-name is :all, it will return all the non-system tables in the database
in fully qualified form: e.g. 'public.test_table'. If string-p is t, the names
will be returned as strings with underscores converted to hyphens.

** function list-table-sizes (&key (schema "public") (order-by-size nil) (size t))
   :PROPERTIES:
   :ID:       d911f929-14c6-4279-96e7-a9dfee4d1f59
   :CUSTOM_ID: 5d66ed97-c2b2-4ac5-aede-d6fb70a983c8
   :END:
→ list

Returns a list of lists (table-name, size in 8k pages) of tables in the current
database. Providing a name to the schema parameter will return just the
information for tables in that schema. It defaults to just the tables in the
public schema. Setting schema to nil will return all tables, indexes etc in
the database in descending order of size. This would include system tables, so
there are a lot more than you would expect. If :size is set to nil, it returns
only a flat list of table names. Setting order-by-size to t will return the
result in order of size instead of by table name.

** function table-exists-p (name)
   :PROPERTIES:
   :ID:       ece4d92b-dd60-434e-b864-e42c743deaa6
   :CUSTOM_ID: 55bb44d8-2732-4257-aabd-d38c5e72ef0f
   :END:
→ boolean

Check whether a table exists in a particular schema. Defaults to the search
path. Takes either a string or a symbol for the table name. The table-name can
be fully qualified in the form of schema.table-name or
database.schema.table-name. If the schema is specified either in a qualified
table-name or in the optional schema-name parameter, we look directly to the
information schema tables. Otherwise we use the search path which can be
controlled by being within a with-schema form.

** function table-size (table-name)
   :PROPERTIES:
   :ID:       bff3f942-2652-401f-9db0-10cc5214191d
   :CUSTOM_ID: bb623170-32c2-43b4-807d-66c34efe9c40
   :END:
→ list

Return the size of a given postgresql table in k or m. Table-name can be either
a string or quoted.

** function table-description (name &optional schema-name)
   :PROPERTIES:
   :ID:       45344f09-e8f2-4f82-a0f8-297623478ad8
   :CUSTOM_ID: ee444ea2-f49f-41c9-905c-177d89770254
   :END:
→ list

Returns a list of the fields in the named table. Each field is represented
by a list of three elements: the field name, the type, and a boolean indicating
whether the field may be NULL.

Table can be either a string or quoted. Table-names can be fully qualified with
the schema or not. If the table-name is not fully qualified and a schema name
is not provided, the table will be assumed to be in the public schema.

** function table-description-plus (table-name)
   :PROPERTIES:
   :ID:       b35cf2c1-7dd0-4676-8f09-2d5679683942
   :CUSTOM_ID: 795b7f54-85ee-4c77-b962-9176f93ad7ac
   :END:
→ list

Returns more table info than table-description. Specifically returns
ordinal-position, column-name, data-type, character-maximum-length, modifier,
whether it is not-null and the default value.

Table can be either a string or quoted. Table-names can be fully qualified with
the schema or not. If the table-name is not fully qualified and a schema name
is not provided, the table will be assumed to be in the public schema.

** function list-columns (table-name)
   :PROPERTIES:
   :ID:       c867f758-86e5-4242-a825-a273c86acfd0
   :CUSTOM_ID: 74baf413-72fb-4f17-abb0-1e7535af33ab
   :END:
→ list

Returns a list of strings of just the column names in a table.
Pulls info from the postmodern table-description function rather than directly.
The table-name can be a string or quoted. Any table-name that is not fully
qualified with the schema will be assumed to be in the public schema.

** function list-columns-with-types (table-name)
   :PROPERTIES:
   :ID:       8dc78de4-32aa-4b28-98c7-02a22ffe036f
   :CUSTOM_ID: 9ada61bd-a670-49f3-8c04-cf025cde431f
   :END:
→ list

Returns a list of (name type) lists for the fields of a table. Returns a list
of strings of just the column names and their sql data types in a table. Pulls
info from the postmodern table-description function rather than directly. The
table-name can be a string or quoted. Any table-name that is not fully qualified
with the schema will be assumed to be in the public schema.

** function column-exists-p (table-name column-name &optional schema-name)
   :PROPERTIES:
   :ID:       491edd0a-7da3-4289-bcea-9482cdfb6df9
   :CUSTOM_ID: 11e937a0-91f6-4475-b393-8f4f2e5d9659
   :END:
→ boolean

Determine if a particular column exists. Table name and column-name can be
either strings or symbols. If the optional schema name is not given or the
table-name is not fully qualified with a schema name, the schema will be assumed
to be the public schema.

** function get-table-oid (table-name &optional schema-name)
   :PROPERTIES:
   :CUSTOM_ID: 8ab55683-e44b-44df-bb11-67909d402383
   :END:
→ integer

Retrieves the oid identifier for a particular table from postgresql. Works
for tables in all schemas.
** function get-table-comment (table-name &optional schema-name)
   :PROPERTIES:
   :CUSTOM_ID: e8d6e402-5c76-4533-9b5c-a823b9582c26
   :END:
→ string

Retrieves the comment, if any attached to the table.
** function rename-table (old-name new-name)
→ boolean

Renames a table. Parameters can be strings or symbols. If you are renaming
a table using a fully qualified schema.table-name, you do not need to
specify the schema in the new-name. You cannot use this function to move
tables from one schema to another. Returns t if successful

** function rename-column (table-name old-name new-name)
→ boolean

Rename a column in a table. Parameters can be strings or symbols. If the table
is not in the public schema, it needs to be fully qualified - e.g. schema.table.
Returns t if successful
* Tablespaces
  :PROPERTIES:
  :ID:       1772a1eb-bc79-4c5f-90d5-2fc10ae49569
  :CUSTOM_ID: tablespaces
  :END:
** function list-tablespaces ()
   :PROPERTIES:
   :ID:       44a29c6a-0002-4660-920f-a9fee4c29471
   :CUSTOM_ID: 70537823-781b-47dd-8c38-9936756c666c
   :END:
→ list

Lists the tablespaces in the currently connected database. What are tablespace
you ask? Per the Postgresql documentation
https://www.postgresql.org/docs/current/manage-ag-tablespaces.html:
Tablespaces in PostgreSQL allow database administrators to define locations in
the file system where the files representing database objects can be stored.
Once created, a tablespace can be referred to by name when creating database
objects.

By using tablespaces, an administrator can control the disk layout of a
PostgreSQL installation. This is useful in at least two ways. First, if the
partition or volume on which the cluster was initialized runs out of space and
cannot be extended, a tablespace can be created on a different partition and
used until the system can be reconfigured.

Second, tablespaces allow an administrator to use knowledge of the usage pattern
of database objects to optimize performance. For example, an index which is very
heavily used can be placed on a very fast, highly available disk, such as an
expensive solid state device. At the same time a table storing archived data
which is rarely used or not performance critical could be stored on a less
expensive, slower disk system.

* Triggers
  :PROPERTIES:
  :ID:       39786cca-6778-4f0b-9187-1f3216b97cda
  :CUSTOM_ID: triggers
  :END:
** function describe-triggers ()
   :PROPERTIES:
   :ID:       10c51511-c1e4-4710-8407-3508fb96333e
   :CUSTOM_ID: 7327ab9a-b79e-4180-8165-434fd4c8d383
   :END:
→ list

List detailed information on the triggers from the information_schema table.
** function list-triggers (&optional table-name)
   :PROPERTIES:
   :ID:       68de46b8-a646-4c1d-9362-747ab1d6cc04
   :CUSTOM_ID: 3bcdabed-dd01-4457-bc18-284598aee0a4
   :END:
→ list

List distinct trigger names from the information_schema table. Table-name can be
either quoted or string. (A trigger is a specification that the database should
automatically execute a particular function whenever a certain type of operation
is performed. Triggers can be attached to tables (partitioned or not), views,
and foreign tables.
See https://www.postgresql.org/docs/current/trigger-definition.html)

** function list-detailed-triggers ()
   :PROPERTIES:
   :ID:       10c51511-c1e4-4710-8407-3508fb96333e
   :CUSTOM_ID: fc3761c2-fc2e-42e4-86f2-0e918c891b5e
   :END:
→ list

* Views
  :PROPERTIES:
  :ID:       a9641e8e-3769-4af4-bdd0-3153e0dd7728
  :CUSTOM_ID: views
  :END:
** function list-views (&optional strings-p)
   :PROPERTIES:
   :ID:       9e9e757e-9efa-4445-9fe1-b66e78f025a8
   :CUSTOM_ID: 4fd820d9-857e-48fa-a62b-e2d72313a10c
   :END:
→ list

Returns list of the user defined views in the current database. When strings-p
is T, the names will be returned as strings, otherwise as keywords.

** function view-exists-p (name)
   :PROPERTIES:
   :ID:       24cd0fc5-8fb0-4b57-9504-71d9520abf6f
   :CUSTOM_ID: f9ba3cce-95e0-45a0-9ede-5654bb71e98e
   :END:
→ boolean

Tests whether a view with the given name exists. Takes either a string or a
symbol for the view name.

** function describe-views (&optional (schema "public")
   :PROPERTIES:
   :ID:       51f383ba-fe58-4a5f-bf31-ac79b18170b7
   :CUSTOM_ID: bbf87da5-981c-42ad-b97e-38c7fafbf8ca
   :END:
→ list

Describe the current views in the specified schema. Includes the select
statements used to create the view. Takes an optional schema but defaults to
public schema.

* Miscellaneous Utility Functions
  :PROPERTIES:
  :ID:       73c18602-c501-4399-ac07-cab915309777
  :CUSTOM_ID: misc-utility-functions
  :END:
** function coalesce (&rest arguments)
   :PROPERTIES:
   :ID:       1df6bd25-618b-4a00-8ec2-cc5b0548b045
   :CUSTOM_ID: 9e576b29-c33d-425d-8759-e8e5e8367593
   :END:
→ value

Returns the first non-NIL, non-NULL (as in :null) argument, or NIL if none are
present. Useful for providing a fall-back value for the result of a query, or,
when given only one argument, for transforming :nulls to NIL.

** function execute-file (filename &optional (print nil))
   :PROPERTIES:
   :ID:       37df40a0-86b4-4aef-828e-68663f74927e
   :CUSTOM_ID: 441f2929-9c04-4b01-8b85-7c474e200755
   :END:
This function will execute sql queries stored in a file. Each sql statement in
the file will be run independently, but if one statement fails, subsequent
query statements will not be run, but any statement prior to the failing
statement will have been commited.

If you want the standard transction treatment such that all statements succeed
or no statement succeeds, then ensure that the file starts with a "begin
transaction" statement and finishes with an "end transaction" statement. See
the test file test-execute-file-broken-transaction.sql as an example.

For debugging purposes, if the optional print parameter is set to t, format will
print the count of the query and the query to the REPL.

IMPORTANT NOTE: This utility function assumes that the file containing the sql
queries can be trusted and bypasses the normal postmodern parameterization of
queries.
** function num-records-in-database ()
   :PROPERTIES:
   :CUSTOM_ID: fcf022af-ae93-470d-be11-23a25acf0bb9
   :END:
→ list

Returns a list of lists with schema, table name and approximate number of
records in the currently connected database.
** function postgres-array-string-to-list (str)
   :PROPERTIES:
   :CUSTOM_ID: 1870a515-3f02-45c6-b42c-97659580f257
   :END:
→ array

Takes a postgresql array in the form of a string like
"{wol=CTc/wol,a=c/wol,b=c/wol}" and returns a lisp array like
    #("wol=CTc/wol" "a=c/wol" "b=c/wol")
** function postgres-array-string-to-array (str)
   :PROPERTIES:
   :CUSTOM_ID: 6fa88adf-cd17-40a8-beb2-0ecea529f6db
   :END:
  "Takes a postgresql array in the form of a string like
\"{wol=CTc/wol,a=c/wol,b=c/wol}\" and returns a lisp list like
  (\"wol=CTc/wol\" \"a=c/wol\" \"b=c/wol\")."
* Imported From s-sql
  :PROPERTIES:
  :ID:       cd3d88e6-1e81-4675-bd17-409efdc39730
  :CUSTOM_ID: b9ec79c0-8e2e-4bad-adcd-e8aa9b6c9a27
  :END:
** macro sql (form)
   :PROPERTIES:
   :ID:       9de76637-62f7-4c7c-a5d1-1f37491b3db3
   :CUSTOM_ID: 8c74e736-6b4f-4996-88c4-f087f46cff05
   :END:
→ string

Convert the given form (a list starting with a keyword) to an SQL query string
at compile time, according to the rules described here. For example:
#+BEGIN_SRC lisp
(sql (:select '* :from 'country :where (:= 'a 1)))
 "(SELECT * FROM country WHERE (a = 1))"
#+END_SRC

but
#+BEGIN_SRC lisp
(sql '(:select '* :from 'country :where (:= 'a 1)))
#+END_SRC

would throw an error. For the later case you need to use sql-compile.

** function sql-compile (form)
   :PROPERTIES:
   :ID:       8d161d2a-06cb-4334-9ee6-86e805eb5295
   :CUSTOM_ID: ace3cbb6-04f0-435b-b2d9-55e2612ea01b
   :END:
→ string

This is the run-time variant of the sql macro. It converts the given list to
an SQL query, with the same rules except that symbols in this list do not
have to be quoted to be interpreted as identifiers. For example:
#+BEGIN_SRC lisp
 (sql-compile '(:select '* :from 'country :where (:= 'a 1)))

  \"(SELECT * FROM country WHERE (a = 1))\"
#+END_SRC

but
#+BEGIN_SRC lisp
(sql (:select '* :from 'country :where (:= 'a 1)))
#+END_SRC
would throw an error. For the later case you need to use sql.

** deftype smallint ()
   :PROPERTIES:
   :ID:       3b558b7d-532c-4375-a80a-4526112ae132
   :CUSTOM_ID: 55a205bf-c9f4-450c-aa86-45cce006ee79
   :END:

  '(signed-byte 16)
** deftype bigint ()
   :PROPERTIES:
   :ID:       d5d5048e-f212-4b5a-ae63-c18d2a411279
   :CUSTOM_ID: 80a15f41-d550-4f3b-adc5-4558d3ddf166
   :END:

  '(signed-byte 64)
** deftype numeric (&optional precision/scale scale)
   :PROPERTIES:
   :ID:       4eb58260-f8e3-4562-bfff-17211cdd98da
   :CUSTOM_ID: 4a38ba2c-b03b-4887-905b-1bf85cd3f607
   :END:

  (declare (ignore precision/scale scale))
  'number
** deftype double-precision ()
   :PROPERTIES:
   :ID:       b4ec051b-d257-47c6-9876-25aec64f967a
   :CUSTOM_ID: 8e094b66-fcc0-4f6e-91dd-5f3c63a7e8a0
   :END:

  'double-float
** deftype bytea ()
   :PROPERTIES:
   :ID:       2532e5a0-cbb5-490a-b142-e971ad0730f7
   :CUSTOM_ID: f4e4e8ac-2d8c-4dea-991f-af57fa589932
   :END:

  '(array (unsigned-byte 8))
** deftype text ()
   :PROPERTIES:
   :ID:       d2867c78-0b66-4b45-882e-115a1192de11
   :CUSTOM_ID: a18ec054-2fcb-482f-bda5-988ab94e9763
   :END:

  'string
** deftype varchar (length)
   :PROPERTIES:
   :ID:       eecec060-840e-42c3-9b6e-74789b19f3ac
   :CUSTOM_ID: d4aa0266-7d2d-4207-909f-8b5767be03fd
   :END:

  (declare (ignore length))
  `string)
** deftype serial ()
   :PROPERTIES:
   :ID:       cc755c1e-af5f-4958-9e18-7b47831cd786
   :CUSTOM_ID: 20cabfe5-d425-422d-a91a-06e7c4cf0a30
   :END:

'integer
** deftype serial8 ()
   :PROPERTIES:
   :ID:       db403045-9608-45f9-8f17-aa3dd951d614
   :CUSTOM_ID: 15d4e630-03c8-4fe0-9b1e-b42a2b42910b
   :END:

'integer

** deftype db-null ()
   :PROPERTIES:
   :ID:       fb204ed8-0ac7-4c74-ad47-ff9e95b75561
   :CUSTOM_ID: f862411e-45cb-4f24-9caa-15edbe804999
   :END:

Type for representing NULL values. Use like (or integer db-null) for declaring a
type to be an integer that may be null."
  '(eql :null)

** function from-sql-name (str)
   :PROPERTIES:
   :ID:       408c0a66-6772-4999-8759-bebeee43646c
   :CUSTOM_ID: 24878142-d801-4fb0-b58b-b59454ee414d
   :END:

Convert a string to a symbol, upcasing and replacing underscores with hyphens.
** function parse-queries (file-content)
   :PROPERTIES:
   :ID:       d9c23921-9839-422d-aeea-df8bfc11df47
   :CUSTOM_ID: 0205cc17-d05d-4ac1-96eb-1c2431e948c8
   :END:
→ list

Read SQL queries in given string and split them, returns a list.
** function read-queries (filename)
   :PROPERTIES:
   :ID:       b871c68d-2b31-444d-8c2d-9d7093fef956
   :CUSTOM_ID: de3bb099-ed34-423a-9bcd-535e1a5f588b
   :END:

Read SQL queries in a given file and split them, returns a list.
** function sql-escape-string (string)
   :PROPERTIES:
   :ID:       02edac61-f915-4d5f-b52e-d4b7ace29352
   :CUSTOM_ID: a6245312-f133-481b-8aed-2bd7c4d4b972
   :END:
→ string

[[http://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS][Escapes]] a string for inclusion in a PostgreSQL query. Example:
#+BEGIN_SRC lisp
 (sql-escape-string \"Puss in 'Boots'\")

 \"E'Puss in ''Boots'''\"

#+END_SRC


** method sql-escape (arg)
   :PROPERTIES:
   :ID:       8b533d2c-53ec-4f34-b19a-fd68bbef9384
   :CUSTOM_ID: 73012d8f-1e5d-4518-8df8-368a4fae3441
   :END:

A generalisation of sql-escape-string looks at the type of the value passed, and
properly writes it out it for inclusion in an SQL query. Symbols will be
converted to SQL names. Examples:
#+BEGIN_SRC lisp
(sql-escape "tr'-x")

"E'tr''-x'"

(sql-escape (/ 1 13))

"0.0769230769230769230769230769230769230"

(sql-escape #("Baden-Wurttemberg" "Bavaria" "Berlin" "Brandenburg"))

"ARRAY[E'Baden-Wurttemberg', E'Bavaria', E'Berlin', E'Brandenburg']"
#+END_SRC
** macro register-sql-operators (arity &rest names)
   :PROPERTIES:
   :CUSTOM_ID: 1723409d-0013-459a-a89c-236d1c7f2fb5
   :END:

Define simple operators. Arity is one of :unary (like
'not'), :unary-postfix (the operator comes after the operand),
:n-ary (like \+ : the operator falls away when there is only one
operand), :2+-ary (like '=', which is meaningless for one operand),
or :n-or-unary (like '-', where the operator is kept in the unary
case). After the arity follow any number of operators, either just a
keyword, in which case the downcased symbol name is used as the
operator, or a two-element list containing a keyword and a name
string.
** variable *escape-sql-names-p*
   :PROPERTIES:
   :ID:       fc3763af-74e4-44ed-903e-7c32be128bd3
   :CUSTOM_ID: 678a9397-e784-42bf-ba21-7d1d8a5816e2
   :END:

Determines whether double quotes are added around column, table, and ** function
names in queries. Valid values:

- T, in which case every name is escaped,
- NIL, in which case no name is escape,
- :auto, which causes only [[http://www.postgresql.org/docs/current/static/sql-keywords-appendix.html][reserved words]] to be escaped, or.
- :literal which is the same as :auto except it has added consequence in
to-sql-name (see below).

The default value is :auto.

Be careful when binding this with let and such ― since a lot of SQL compilation
tends to happen at compile-time, the result might not be what you expect. Mixed
case sensitivity is not currently well supported. Postgresql itself will
downcase unquoted identifiers. This will be revisited in the future if requested.

** function to-sql-name (name &optional (escape-p *escape-sql-names-p*) (ignore-reserved-words nil))
   :PROPERTIES:
   :ID:       1b4f5a57-87f7-42f5-ae3c-eff5b41122b3
   :CUSTOM_ID: 3cbda7a6-974c-475d-a87c-90353ac15b75
   :END:

Convert a symbol or string into a name that can be a sql table, column, or
operation name. Add quotes when escape-p is true, or escape-p is :auto and the
name contains reserved words. Quoted or delimited identifiers can be used by
passing :literal as the value of escape-p. If escape-p is :literal, and the
name is a string then the string is still escaped but the symbol or string is
not downcased, regardless of the setting for *downcase-symbols* and the hyphen
and forward slash characters are not replaced with underscores.

Ignore-reserved-words is only used internally for column names which are allowed
to be reserved words, but it is not recommended.

** condition sql-error
   :PROPERTIES:
   :ID:       800c314e-4ff7-435e-84ea-fe6d3ec71353
   :CUSTOM_ID: 2970d836-dcaa-4b49-aa95-27aa9d3d4f3f
   :END:
        No documentation provided.


* Conditions Imported From cl-postgres
  :PROPERTIES:
  :ID:       800ef5ef-fa19-428d-83b9-f38581e38d09
  :CUSTOM_ID: 5ccb5ff2-0d42-48d4-90c0-2ef6e7f8f1c7
  :END:
** condition database-connection-error
   :PROPERTIES:
   :ID:       5d0fdf49-8efa-4e7e-8b9d-925cb19630e1
   :CUSTOM_ID: b16b281c-2103-4f65-bb48-d9ac0083a302
   :END:

Conditions of this type are signalled when an error occurs that breaks the
connection socket. They offer a :reconnect restart.

** condition database-error
   :PROPERTIES:
   :ID:       0ce0752e-d58b-4072-9de1-8c791ab627d0
   :CUSTOM_ID: 06f35002-f176-4bae-b9cc-271b8b3b2cf1
   :END:

This is the condition type that will be used to signal virtually all
database-related errors (though in some cases socket errors may be raised when
a connection fails on the IP level).
*** reader database-error-code
    :PROPERTIES:
    :CUSTOM_ID: 15654c72-6edc-4fec-8526-d15dbfda6e44
    :END:

Code: the Postgresql SQLSTATE code for the error
 (see the Postgresql Manual Appendix A for their meaning). Not localizable.
 Always present.

*** accessor database-error-message
    :PROPERTIES:
    :CUSTOM_ID: 94776637-29c8-4966-9105-c00e13c1ec1d
    :END:

Message: the primary human-readable error message. This should be accurate
but terse (typically one line). Always present.

*** reader database-error-detail
    :PROPERTIES:
    :CUSTOM_ID: b01df60b-76be-43a3-9d80-13722658bb55
    :END:

Detail: an optional secondary error message carrying
more detail about the problem. Might run to multiple lines or NIL if none is
available.

*** reader database-error-query
    :PROPERTIES:
    :CUSTOM_ID: 91ab0c67-4276-4eb1-8de9-4028f7f778f7
    :END:
Query that led to the error, or NIL if no query was involved.

*** reader database-error-cause
    :PROPERTIES:
    :CUSTOM_ID: 3262d3c4-53a7-4f81-9d09-ccee5bf59b66
    :END:
The condition that caused this error, or NIL when it was not caused by another condition.

** function database-error-constraint-name (err)
   :PROPERTIES:
   :ID:       300b1531-c01f-4674-b08c-4624d5502a5c
   :CUSTOM_ID: 77cc7700-9573-4280-ba3a-cb368fa96dcc
   :END:

Given a database-error for an integrity violation, will attempt to
extract the constraint name.

** function database-error-extract-name (err)
   :PROPERTIES:
   :ID:       91e02238-2910-47d1-9fdd-c466147fe69c
   :CUSTOM_ID: 52fe59d2-396d-4c36-9a94-5ef452702d79
   :END:

Given a database-error, will extract the critical name from the error message.
