#+TITLE: S-SQL Examples V
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>
#+OPTIONS: ^:nil

* [[file:s-sql-examples.org][S-SQL Examples Home Page]]
| [[file:s-sql-a.org][A]]| [[file:s-sql-b.org][B]]| [[file:s-sql-c.org][C]]| [[file:s-sql-d.org][D]]| [[file:s-sql-e.org][E]]| [[file:s-sql-f.org][F]]| [[file:s-sql-g.org][G]]| [[file:s-sql-h.org][H]]| [[file:s-sql-i.org][I]]| [[file:s-sql-j.org][J]]| [[file:s-sql-k.org][K]]| [[file:s-sql-l.org][L]]| [[file:s-sql-m.org][M]]| [[file:s-sql-n.org][N]]| [[file:s-sql-o.org][O]]| [[file:s-sql-p.org][P]]| [[file:s-sql-r.org][R]]| [[file:s-sql-s.org][S]]| [[file:s-sql-t.org][T]]| [[file:s-sql-u.org][U]]| [[file:s-sql-v.org][V]]| [[file:s-sql-w.org][W]]|  [[file:s-sql-special-characters.org][Special Characters]]                        |  [[file:calling-postgresql-stored-functions.org][Calling Postgresql Stored Functions and Procedures]]|

* Variable Parameters
  :PROPERTIES:
  :CUSTOM_ID: variable-parameters
  :END:
You can use variables in s-sql statements. For example:
#+begin_src lisp
  (let ((column 'latitude) (table 'countries))
               (query (:select column :from table)))

  (let ((select 'countries.name))
               (query (:select select
                     :from 'countries 'regions
                     :where (:and
                             (:or (:= 'regions.name '$1)
                                  (:= 'regions.name '$2))
                             (:= 'regions.id 'countries.region-id)))))
  #+end_src
  Notice that the variable values were quoted. If you used strings, the string would be escaped and Postgresql would give you a syntax error.

* View (:create-view)
  :PROPERTIES:
  :CUSTOM_ID: create-view
  :END:
Create-view will accept quoted values, strings or keywords for the name of the view you are creating. Hyphens will be automatically be converted to underscores.
#+begin_src lisp
 (query (:create-view 'quagmire (:select 'id 'name :from 'employee)))

 (query (:create-view :quagmire (:select 'id 'name :from 'employee)))

 (query (:create-view "quagmire" (:select 'id 'name :from 'employee)))

 (query (:create-view 'quagmire-hollow (:select 'id 'name :from 'employee)))

 (query (:create-view "quagmire-hollow" (:select 'id 'name :from 'employee)))

#+end_src
